### ISSUE TITLE
Vuforia only uses front camera on XPS 13 "2-in-1" laptop during Play Mode in Unity

### ISSUE THREAD

**Issue by oqoobo** [PTCInc/vuforia-engine#1]
**Summarize the bug:**
Vuforia uses the camera on the wrong side of the device.

**Observed problem**
Instead of using the back camera as intended, Vuforia in Unity only uses the Front Camera

**Expected result**

**Other observations**
Share any other observations that you made while experiencing the bug.

**Reproducible steps**
1. Set up any Vuforia Unity Project on an XPS 13 2-in-1

**Affected Vuforia Engine version:**
E.g. v10.12.3.

**Affected platform:**
 - Workstation OS: [e.g. Windows, Mac]
 - Platform [e.g. Unity, Apple Xcode, Android Studio]
 - Platform version [e.g. 2021.3.1f1]

**Affected device:**
 - Name: [e.g. Google Pixel 6a]
 - Model: [e.g. GX7AS]
 - OS: [e.g. Android 12]

**Screenshots / Video Recordings**
Share any screenshots or video recordings from the platform or device. You can also use the [Session Recorder](https://library.vuforia.com/platform-support/recording-and-playback).

**Affected database**
If applicable, share your database / dataset which is affected in the issue you're experiecing.

**Device or platform logs**
```Share any logs from the platform or device.```

**Workaround**
Is there currently a workaround that you're using?

**Additional comments**
Add any other details about the problem here.

**Comment by ptc-pscheper** [comment]
Hi there,

Thanks for reaching out. Could you please share the following extra information?

- Affected Unity version
- Affected Vuforia Engine version
- XPS 13 Model Name
- Windows version

I've also asked internally the team if there's a possibility to switch the cameras during play mode. 

Thanks!

**Comment by ptc-pscheper** [comment]
There's not an API within the Vuforia Configuration to switch cameras, but I would recommend to disable one of the cameras via the Device Manager of Windows. That might work.
