### ISSUE TITLE
Concerns about Galaxy Tab S8 5G - Flashlight - Android 14 & Recommended devices

### ISSUE THREAD

**Issue by tsoen** [PTCInc/vuforia-engine#102]
**Summarize your device feedback**
Hello,
We have a Galaxy Tab S8 5G (SM-X706B), which is listed in the Vuforia recommended devices (https://developer.vuforia.com/library/platform-support/recommended-devices).
When I got my hands on it a few weeks back, it was still on Android 12.
I started using it for Vuforia development.
At the time, the Flashlight feature from Vuforia was working on the device.
Then, a few days back, the tablet system was updated to Android 14.
Since then, the Flashlight feature stopped working on the tablet (`Failed to set camera flash mode` error).

We are using Vuforia v10.19.3
We are using Unity 2022.3.17f1 (LTS).
Our project is targeting Android 13 (API 33) for the moment.
I quickly tried targetting Android 14, but got an error (`One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts`). I did not dig further yet.

This raises a few questions:
- Vuforia supported versions (https://developer.vuforia.com/library/platform-support/supported-versions) mentions Android 8.0+. Is Android 14 actually supported as it implies ? If so, I will try to see if I can fix the error to target Android 14 and see if the issue persists.
- What does it mean for a device to be in the recommended devices list ? Should we expect ALL the features (including the flashlight) to be working on the devices in this list ?

**Business Impact**
Cannot use flashlight feature on a Vuforia recommended device.

**Link to device manufacturer / device specifications**
Galaxy Tab S8 5G (SM-X706B).
Android 14.

Regards

**Comment by tsoen** [comment]
@ptc-pscheper I don't think there is any more interesting log... is there something I should enable ? The `VuforiaConfiguration` Log Level is already set to `ALL` in the inspector.
Here is what I see from the Android Logcat :

![image](https://github.com/PTCInc/vuforia-engine/assets/46613250/2ccfc6f8-b5fc-43d2-abf4-1d2b9b58ddf8)

**Comment by tsoen** [comment]
Note: we register to the pixel format RGB888 and try to enable the flash (to check if it works) in the `VuforiaApplication.Instance.OnVuforiaStarted` event.

**Comment by ptc-aeveritt** [comment]
Hi @tsoen - Flash mode control is not supported when using ARCore on Android, is it possible that the upgrade to Android 14 has introduced ARCore support on the device and Vuforia Engine is now using ARCore?
The log screenshot above appears to show ARCore is in use (session.cc and ArConfig) which would explain flash mode control not being possible.

**Comment by tsoen** [comment]
Hi @ptc-aeveritt - Sadly I can't check anymore if it was using ARCore back then, but I guess you must be right.
May I suggest that the Flash mode control limitation with ARCore should be added to documentation (https://developer.vuforia.com/library/platform-support/working-camera-unity) ? The page mentions limitation with ARCore for Focus region and Exposure region, but there is no mention of the Flash with ARCore.

**Comment by ptc-pscheper** [comment]
I will make sure the flash mode control limitation will be highlighted in the documentation. In the past flashlight control seemed to work properly on most ARCore enabled devices but the past months we've seen more and more having the issue. I can only imagine the frustration on your side, so apologies we cannot be more of help as this is on Google's side.

For future reference and for others, this is a highly requested feature on the ARCore issue tracker: https://github.com/google-ar/arcore-android-sdk/issues/153 & https://github.com/google-ar/arcore-android-sdk/issues/356.

**Comment by tsoen** [comment]
Hello @ptc-pscheper,
Thank you for the feedback.
Sadly, seeing it has been 6+ years since the creation of these tickets on ARCore side, I doubt they will ever do something about it 😢

**Comment by ptc-pscheper** [comment]
Yes, I completely share your doubts. I am sorry 🙁
