### ISSUE TITLE
VuMark Images (PNG, PDF, SVG) appear corrupted after generating within Target Manager

### ISSUE THREAD

**Issue by madhu-dcs** [PTCInc/vuforia-engine#103]
**Summarize the bug:**
VuMark generation through the Vuforia developer portal results in corrupted PNG, PDF, and SVG image outputs.

**Observed problem**
When attempting to generate a Vumark through the Vuforia developer portal, the downloaded PNG, PDF, and SVG files appear corrupted. This manifests as:

PNG: The image is displaying error when opening with windows photos -  "its looks like we dont support this file format".
PDF: The PDF might not open correctly, showing an error message.
SVG: The SVG file could be unreadable by image editing software.

**Expected result**
The downloaded Vumark image files (PNG, PDF, SVG) should be clear, visually accurate representations of the Vumark pattern, without any corruption.

**Other observations**
* The issue seems to affect all downloadable Vumark image formats & databases & also tried with other account but having same issue.
* There are no error messages displayed during the Vumark generation process.

**Reproducible steps**
1. Log in to the Vuforia developer portal.
2. Navigate to the Target Manager where you want to generate a Vumark from database.
3. Generate VuMark - Enter ID  
4. Click on the "Download" button for the desired image format (PNG, PDF, SVG).
5. Open the downloaded image file.
6. Observe the corruption in the image

**Affected Vuforia Engine version:**
(Not applicable in this case)

**Affected platform:**
(Not applicable in this case)

**Affected device:**
(Not applicable in this case)

**Screenshots / Video Recordings**
![image](https://github.com/PTCInc/vuforia-engine/assets/124144204/e17772ef-326f-4fb7-bf51-beadb0652a22)

**Affected database**
All VuMark databases

**Device or platform logs**
(Not applicable in this case)

**Workaround**
Currently, there is no known workaround for this issue.

**Additional comments**
None

**Comment by ptc-pscheper** [comment]
Hi there, thank you for your bug report. I have identified and acknowledge the issue and have reported this within our team. I will update this thread as soon as possible with more information. Currently there is indeed no workaround.

**Comment by ptc-pscheper** [comment]
Our team is preparing a hotfix to be pushed still today! Stay tuned.

**Comment by ptc-pscheper** [comment]
The fix is deployed and you should now be able to generate VuMark images for all graphic formats. Please re-open the ticket if you still experience any issues. I apologize for the inconveniences this might have caused you.

**Comment by madhu-dcs** [comment]
Thank you @ptc-pscheper . Now its working fine and able to generate VuMark in all formats
