### ISSUE TITLE
Cannot download database

### ISSUE THREAD

**Issue by w1126l** [PTCInc/vuforia-engine#107]
Just wanted to mention that I'm very new to Vuforia and Unity!

**Summarize the bug:**
I cannot download the image target database. I only have three images so far.

**Observed problem**
Whenever I try to download the database, it loads for a very long time and then sends out an error that I should try again later or contact support. The error reads: "Try Again It is taking too long to download this device database, please try again. If the issue continues, please reach out via the Support Center."

**Expected result**
I wanted to download the database to plug into Unity.

**Affected Vuforia Engine version:**
v10.22.

**Affected platform:**
 - Workstation OS: Windows
 - Platform: Unity
 - Platform version [e.g. 2022.3.19f1]

**Comment by ptc-pscheper** [comment]
Hi there, can you share your database name and the first few characters of the UUID? The UUID can be found in the URL when navigating to the database. 

For example: `https://developer.vuforia.com/vui/develop/databases/[YOUR_DATABASE_UUID]/targets`

**Comment by w1126l** [comment]
> Hi there, can you share your database name and the **first few characters of the UUID**? The UUID can be found in the URL when navigating to the database. 
> 
> 
> 
> For example: `https://developer.vuforia.com/vui/develop/databases/[YOUR_DATABASE_UUID]/targets`

Name: test 1
UUID (some characters): 9970a6aa6cafm

**Comment by ptc-pscheper** [comment]
Hi there, could you re-try downloading your database and let me know the outcome? We are not able to reproduce the error.

**Comment by ptc-pscheper** [comment]
This issue is closed due to inactivity. Feel free to re-open or create a new bug report in the future.

**Comment by ghettokon** [comment]
Hi, I also run into the same problem:

Name: BigVUMARK
UUID: d070d8f192294284844d00cc6e11e44b

Generate VuMark is not working either... 

I've tried both Chrome and Firefox (fresh install), both timed out, so it is not a browser problem?

please help!
