### ISSUE TITLE
Webcam can not be accessed in Unity / OSX Ventura

### ISSUE THREAD

**Issue by wirmachenbunt** [PTCInc/vuforia-engine#11]
When using the playmode in Unity (OSX Ventura), the webcam does not work, the screen stays black or i get a message that the webcam use is not auhorized, depending on the Unity version.

Checking the security options in OSX ventura, there seems no option to grant access to the webcam for Unity/Vuforia

Testing the project in windows, the webcam preview works. So it seems this is a OSX Ventura issue. 

This is the most basic Untiy Vuforia Setup, ARCam with Imagetarget.

Building the project to iOS, the iPad Camera does work with the project. Only the playmode preview does not work. Any idea how to solve this ? Is this a known issue ? How to authorize the Facetime Camera for Unity / Vuforia ?

Vuforia Engine 10.14
OSX Ventura
Unity3D 2021 / 2022 / 2023 - Apple Silicon Version

Macbook Pro M1 Max

**Comment by ptc-pscheper** [comment]
Hi there, thank you for the bug report. Can you check if the issue is reproducible via our [Core Samples](https://assetstore.unity.com/packages/templates/packs/vuforia-core-samples-99026) and Unity 2021.3 or above? Thank you!

**Comment by ptc-pscheper** [comment]
One of our R&D colleagues updated to OSX Ventura (13.2.1) on their Macbook Pro M1 (Silicon) and was not able to reproduce your issue. Did you verify that you allowed the Unity Hub to access your camera?

![image](https://user-images.githubusercontent.com/88328882/229197769-90ed5aa1-589f-471d-a43e-3a115f48782f.png)

**Comment by ptc-pscheper** [comment]
One of our R&D colleagues updated to OSX Ventura (13.2.1) on their Macbook Pro M1 (Silicon) and was not able to reproduce your issue. Did you verify that you allowed the Unity Hub to access your camera?

![3uRhArsqY1](https://user-images.githubusercontent.com/88328882/229197984-c0db59d5-e9cf-4be6-bac6-2d6a10e82675.png)

**Comment by wirmachenbunt** [comment]
Hey, thank you for the hints, unity hub was enable. i just turned it on and off and then tried the core samples from the asset store. one example showed successfully the camera. consider this not an issue.

maybe osx lost the security setting after updating to ventura.  definetly not a vuforia issue. 

thanks for helping anyway.  i'm looking forward to make a project with it.
