### ISSUE TITLE
Unable to find library for ID classic in Xcode

### ISSUE THREAD

**Issue by JafferArshad** [PTCInc/vuforia-engine#113]
Unable to find library for ID classic in Xcode

**Comment by ptc-pscheper** [comment]
Your issue has been closed as it does not follow our contribution guidelines. To ensure effective and timely support, it is mandatory to follow the guidelines and use our provided templates when submitting a bug report or feature feedback. However, I encourage you to re-submit your report or feedback using the appropriate template. 

You can find xCode specific documentation here: https://developer.vuforia.com/library/getting-started/getting-started-vuforia-engine-ios-development

Please check out our [Contribution Guidelines](https://github.com/PTCInc/vuforia-engine/blob/master/CONTRIBUTING.md) for issue requirements. 

Thank you!
