### ISSUE TITLE
Vuforia aab + split binary >150MB

### ISSUE THREAD

**Issue by MtionBra1n** [PTCInc/vuforia-engine#114]
Hey there,

I'm experiencing a persistent issue where the Vuforia database is not recognized when I build my app as an Android App Bundle (AAB) with split binary options. However, when I build the project as an APK or < 150MB, everything functions correctly.

Here's what I've explored so far:

I understand that there are specific considerations with the StreamingAssets folder in AAB, such as potential delays in downloading contents. I attempted to package the Vuforia database using AssetBundles. Unfortunately, it seems that the .dat file cannot be included in an AssetBundle. For reference, the app does upload and I can open it. It is just Vuforia which doesnt work!

I have a loading scene in Unity and my main Scene which gets loaded after

Setup Details:

```
Unity 2022.3.25f1 / 2022.3.19f1
Vuforia 10.22.5
Build App Bundle (Google Play) [Check]
Split Application Binary [Check]

Base Scene Size: ~50MB
Main Scene Size: ~1.5GB
```

I've spent numerous hours over several nights trying to resolve this without success. Does anyone have suggestions on how to ensure the Vuforia database is properly recognized and loaded in an AAB format? Any insights or fixes would be greatly appreciated.

My Question at the unity forum 
https://forum.unity.com/threads/how-to-make-vuforia-with-aab-and-split-binary-work.1582065/

Thank you

**Comment by ptc-pscheper** [comment]
Hi there, Vuforia Engine doesn't officially support the possibility to use the `Split Application Binary` feature of Unity. However I've requested our engineering team to check if this is currently possible.

**Comment by ptc-pscheper** [comment]
This issue is closed due to inactivity. Feel free to re-open or create a new bug report in the future.
