### ISSUE TITLE
Unity crash issue

### ISSUE THREAD

**Issue by devadarshinim** [PTCInc/vuforia-engine#115]
I am working on vuforia model target. The unity get crashed while opening the project.

I worked both on vuforia image target and model target. While working on image target I could able to work on unity projects, but after importing model target packages I could not able to open the project. It keeps on crashing.

I had tried reinstalling the entire unity hub and editor but still there is no use.

I had connected with the unity team too. They informed that the issue is not related to unity. Its regarding the code or vuforia related issue.

Affected Vuforia Engine version:
2022.3.22f1

**Comment by ptc-pscheper** [comment]
Please share your Model Target Database via vuforia-feedback@ptc.com and tag this issue. Can you also add reproducible steps, for example, did you just create a new Unity project and added the SDK to it? Also what Engine SDK version are you using? Thank you.
