### ISSUE TITLE
GuideView not visibile with MRTK3 | HoloLens

### ISSUE THREAD

**Issue by HaiKonofanDesu** [PTCInc/vuforia-engine#12]
**Summarize the bug:**
Guide View not Visible with MRTK3 Camera

**Observed problem**
When adding the Vuforia Behaviour script to the Main Camera in the MRTK XR Rig the Guide View is not visible. Probably due to clipping limited to 0.01 and the GuideViewRenderer spawing at 0/0/0. Moving the Z to something like 0.1 manually makes it visible but A) Way to small B) I see 2 GuideViews then (one per eye). Only when I then also update the scale to 10 I can see the overlay but then the Tracking does not work.

**Expected result**
I see a Guide View from the start and can scan my object

**Other observations**
Some of the Docs seems to be out of date. 
https://library.vuforia.com/platform-support/working-hololens-sample-unity -> There is no VuforiaAdditiveSceneLoader Script anywhere in the Demo Project.
The whole category "Target GameObjects" also seems outdated as these Scripts did not get used in the example. I just want to track a simple cup for now to see how good it works

**Reproducible steps**
Activate Beta in the MixedRealityFeatureTool
Get the MRTK3 Scripts and OpenXR
Import Vuforia (newest Version)
Place MRTK XR Rig in Scene (after applying the MRTK Settings)
Place Vuforia Behavior Script on Camera
Set Model
Start Holographic Remoting

**Affected Vuforia Engine version:**
add-vuforia-package-10-14-4.unitypackage

**Affected platform:**
 - Workstation OS: Windows
 - Platform Unity + Windows UWP (aka Hololens 2)
 - Platform version 2021.3.15f1

**Affected device:**
 - Name: HoloLens 2

**Screenshots / Video Recordings**
Not.. much to record as you can't see it. All I can say is that clicking on the Camera in Unity shows the outline beeing visible in the Camera but I guess that's a problem with the clipping

**Workaround**
Moving the Plane works with the visibility but not with the tracking, tho the tracking could be a problem with the model, not sure.

**Additional comments**
an updated MRTK3 Package or at least tutorial would be appreciated

**Comment by ptc-pscheper** [comment]
Sadly Vuforia Engine is not fully compatible, as of today, with MRTK v3.0. The latest tested and verified version to use Vuforia Engine with is MRTK v2.8. I would suggest creating another ticket to track a request for us to support MRTK v3.0+ with your use-cases and business opportunity: 

![msedge_hz4LmkLDpx](https://user-images.githubusercontent.com/88328882/229118886-48d37aa2-1804-4d8b-9dfb-5e4feab764a6.gif)
