### ISSUE TITLE
STATUS_INFO INSUFFICIENT_FEATURES never triggers for bad targets.

### ISSUE THREAD

**Issue by yosun** [PTCInc/vuforia-engine#121]
**Summarize the bug:**
`STATUS_INFO INSUFFICIENT_FEATURES never triggers for bad targets.`

**Observed problem**
`STATUS_INFO INSUFFICIENT_FEATURES never triggers for bad targets.`

**Expected result**
STATUS_INFO INSUFFICIENT_FEATURES should show for bad targets.

**Other observations**
Share any other observations that you made while experiencing the bug.

**Reproducible steps**

1) Create an Image Target using a bad target such as a blank white image. 
2) Notice that STATUS_INFO does not display insufficient features! 

**Affected Vuforia Engine version:**
E.g. v10.12.3.

**Affected platform:** 
 - Platform  Unity Mac Silicon
 - Platform version 2023.1.16f1

**Affected device:**
 - Name: [e.g. Google Pixel 6a]
 - Model: [e.g. GX7AS]
 - OS: [e.g. Android 12]

**Screenshots / Video Recordings**
Share any screenshots or video recordings from the platform or device. You can also use the [Session Recorder](https://library.vuforia.com/platform-support/recording-and-playback).

**Affected database**
If applicable, share your database / dataset which is affected in the issue you're experiecing.

**Device or platform logs**
```Share any logs from the platform or device.```

**Workaround**
Is there currently a workaround that you're using?

**Additional comments**
Add any other details about the problem here.

**Comment by ptc-pscheper** [comment]
Can you please share your database UUID and database name via vuforia-feedback@ptc.com? The UUID can be found within the URL when navigating to the database in the Target Manager.
