### ISSUE TITLE
is there Record asset with Vuforia AR

### ISSUE THREAD

**Issue by semi67764** [PTCInc/vuforia-engine#124]
i made Unity proejct, is there Record Screen with AR object in Android and IOS?

if yes, could you recommend me asset?

because i searched many thing, and tried by myself,

something can take record in PC only not Android, something can take record in mobile too but it didn't take record with AR object(it was Vuforia Session record)

**Comment by ptc-thesbyro** [comment]
Your issue has been closed as it does not follow our contribution guidelines. To ensure effective and timely support, it is mandatory to follow the guidelines and use our provided templates when submitting a bug report or feature feedback. However, I encourage you to re-submit your report or feedback using the appropriate template. 

Please check out our [Contribution Guidelines](https://github.com/PTCInc/vuforia-engine/blob/master/CONTRIBUTING.md) for issue requirements. 

Thank you
