### ISSUE TITLE
Error al abrir la licencia

### ISSUE THREAD

**Issue by arielDavid-oss** [PTCInc/vuforia-engine#126]
al entrar a la pagina de vuforia y quiero hacer una nueva licencia basica y entrar a la licencia se tarda y despues muestra un error que no esta disponible temporalmente 
![Captura de pantalla 2024-05-28 224551](https://github.com/PTCInc/vuforia-engine/assets/139005610/6d8325ee-2a57-4d6e-9844-b101c8c38ae8)

**Comment by ptc-thesbyro** [comment]
Your issue has been closed as it does not follow our contribution guidelines. To ensure effective and timely support, it is mandatory to follow the guidelines and use our provided templates when submitting a bug report or feature feedback. However, I encourage you to re-submit your report or feedback using the appropriate template. 

Please check out our [Contribution Guidelines](https://github.com/PTCInc/vuforia-engine/blob/master/CONTRIBUTING.md) for issue requirements. 

Thank you
