### ISSUE TITLE
How does area target tracking work?

### ISSUE THREAD

**Issue by thechargedneutron** [PTCInc/vuforia-engine#127]
Hi, I am curious about how the area target works. This is important for me when developing methods to understand where the localization can potentially fail and what remedies should I have in case it does. Here are some questions that would be nice to have answers on:

1. Does the area target localization use prior location measures? For example, if an object A is next to the object B and the localization was correct at A and the person moves to B. Is the probability of saying you are close to B more than any other object X given that A was correctly localized a while back? Is the feature matching weighted by prior location? If not, this should be implemented externally by me for my use case.

2. What happens when the tracking is lost? Does Vuforia use other sensors like accelerometer or gyroscope to continue updating the location or is that not reliable? I observed when the tracking is lost the (x, y, z) position still remains around the point where the tracking was lost, so want to confirm if that is arbitrary or uses some less-reliable tracking?

3. Apart from the extended tracking checkbox, are there other ideas in or beyond Vuforia's implementation that can be used to improve long-range tracking and movement?

Feel free to point me to related research work if the implementation is inspired by some research or well-known algorithm like SIFT + tracking or Kalman Filter smoothing. I am a researcher in computer vision, so would not mind reading papers to understand the functionality :)

**Comment by ptc-emaggio** [comment]
@thechargedneutron thanks for the enquiry. As standard practice we do not provide information about the algorithms and inner workings of the Vuforia features. Still we are happy to get feedback on eventual gaps in [our documentation](https://developer.vuforia.com/library/environments/area-targets).

Regarding question 2. if the Area Target cannot be localized Vuforia indeed uses Sensors and device capabilities (see [Vuforia Fusion](https://developer.vuforia.com/library/environments/vuforia-fusion)) to provide an extended tracking experience. Still, as the target is not actively tracked, the Vuforia output might become less accurate over time.
