### ISSUE TITLE
Vuforia Creator App - missing "Capture Area"

### ISSUE THREAD

**Issue by CJBRAVO2** [PTCInc/vuforia-engine#132]
Downloaded creator app to IPAD AIR 5

missing in the app the 'capture area' feature...

only have 'import' and 'record session'.

![image](https://github.com/PTCInc/vuforia-engine/assets/172478374/b90ced87-0227-4983-bfc2-df7ad087ad00)

**Comment by ptc-thesbyro** [comment]
Hi,

The "Capture Area" is only available on devices with a LiDAR sensor. At this current time, only the **Pro** and **Pro Max models** of the iPhone 12, 13, 14, and 15, as well as the third-generation 11-inch and fifth-generation 12.9-inch iPad Pro models from 2020 and later include a LiDAR sensor.

For more information, please see the [Creator App](https://developer.vuforia.com/library/tools/creator-app) guide under Device Compatibility.

I will close the ticket, as this isn't a bug but a hardware limitation.

Hope it helps,

**Comment by CJBRAVO2** [comment]
Hi,
yes, I see now under the comments.. I missed that, i assumed all the devices listed were capable of the scanning.

thanks,

P.s. 
in the creator app, when trying to reach 'user guide' it times out on the external link.

**Comment by ptc-thesbyro** [comment]
Oh, we'll get that fixed!

Thanks for letting us know.
