### ISSUE TITLE
Hololens vuforia sample can't work properly in Hololens2 

### ISSUE THREAD

**Issue by begkonfrank** [PTCInc/vuforia-engine#134]
**Summarize the bug:**
Hololens vuforia sample can't work properly in Hololens2

**Observed problem**
The sample can work perfectly well on unity and PC camera. However when install on Hololens2, the app will only display the beginning "Vuforia Engine" and will show nothing and have no response at all.

**Reproducible steps**
1. I have the license key on vuforia camera
2. the setting are as follows
![微信图片_20240618105518](https://github.com/PTCInc/vuforia-engine/assets/167400404/6cbcbd72-6bf7-4d42-a9ab-0c502cfe32dc)
![微信图片_202406181055181](https://github.com/PTCInc/vuforia-engine/assets/167400404/4f9b89b8-f18f-4cfa-9c8e-bce007d646a4)
![微信图片_202406181055182](https://github.com/PTCInc/vuforia-engine/assets/167400404/d47cb0e3-06da-497f-b17f-5900a41e7a01)
![微信图片_202406181055183](https://github.com/PTCInc/vuforia-engine/assets/167400404/0675d10c-daa1-4c3d-aa15-7463f9707e07)

**Affected Vuforia Engine version:**
E.g. v10.22.5

**Affected platform:**
unity 2022.3.25f1

**Affected device:**
Hololens2

**Comment by ptc-thesbyro** [comment]
Hi, 

Please try our new sample and see if the problem persists. You can find a guide for it [here](https://developer.vuforia.com/library/platform-support/vuforia-digital-eyewear-sample)

Thank you,
