### ISSUE TITLE
 Vuforia Engine 10.24 is Available!

### ISSUE THREAD

**Issue by ptc-thesbyro** [PTCInc/vuforia-engine#135]
Vuforia Engine 10.24.4 is now available!

The Vuforia Engine team is happy to announce the release of our newest version of the Vuforia Engine. Below is a summary of the key updates in this release. For the complete list, check out the [release notes](https://library.vuforia.com/release-notes/vuforia-engine-release-notes).

New Improvements:

- **New Digital Eyewear Unity sample app:** A [new sample app](https://developer.vuforia.com/library/platform-support/vuforia-digital-eyewear-sample) available in the Unity Asset Store demonstrates how to create a Vuforia Engine app for both HoloLens 2 and the Magic Leap 2, using MRTK 3.
- **Observation Preset for Advanced Model Targets:** In the Model Target Generator, use the new [Observation Preset](https://developer.vuforia.com/library/model-targets/advanced-views#observation-for-stationary-objects) to enable recognition of Advanced Model Targets with the target fully in view and for close-up views, depending on object size.
- **Runtime Guide Views for Advanced Model Targets:** Advanced Model Targets now also support Guide View images, which, when enabled, are generated and shown at runtime.
- **Improved diagnostics:** A new [API](https://developer.vuforia.com/library/sites/default/files/references/native/group__EngineLogHandlerConfigGroup.html) is available to retrieve log messages at runtime.
- **Access to depth frames:** On iOS devices running ARKit, Vuforia Engine now exposes access to depth frames at runtime. Enable depth with this [API](https://developer.vuforia.com/library/sites/default/files/references/native/group__CameraControllerGroup.html#gabaa0ba1badb9f8ddbd02e5a8e38c525f) call.
- **Improved Model Target stability:** When creating Model Targets with the [MTG CLI](https://developer.vuforia.com/library/model-targets/cli#uncertain-parts), individual parts of the CAD model can now be marked as uncertain, e.g., for moving parts.
- **Part-based views for Advanced Model Targets:** [Recognition for Advanced Model Targets](https://developer.vuforia.com/library/web-api/model-target-web-api#create-an-advanced%C2%A0model%C2%A0target-dataset) can now be controlled by specifying a part that will be in view when the target is recognized, e.g., for inspection scenarios.
- **Session Recorder Conversion Tool:** A new tool is available to [convert session recordings](https://developer.vuforia.com/library/platform-support/recording-and-playback#session-recordings-backward-compatibility) created with Vuforia Engine 10.20 or newer into a format that Vuforia Engine 10.19 and older can use. You can access the tool from the [downloads page.](https://developer.vuforia.com/downloads/tools)

Other notes:

- The minimum supported Lumin SDK for Magic Leap is now 1.6.0+.
- The Vuzix M400 device is no longer supported.

**Comment by alamboley** [comment]
Hello,

Thanks for this update! Trying to build the **New Digital Eyewear Unity sample app**, I've this error: BuildFailedException: Vuforia Digital Eyewear Sample requires the Hand Tracking feature to be enabled.

I tried to add *Hand Interaction Profile* in *Enabled Interaction Profiles* but without luck. Any ideas?
