### ISSUE TITLE
model target

### ISSUE THREAD

**Issue by FQY681** [PTCInc/vuforia-engine#136]
It is possible to add multiple images in the software, but not multiple models. Is there any solution to this problem? Looking forward to your reply!

**Comment by ptc-thesbyro** [comment]
Your issue has been closed as it does not follow our contribution guidelines. To ensure effective and timely support, it is mandatory to follow the guidelines and use our provided templates when submitting a bug report or feature feedback. However, I encourage you to re-submit your report or feedback using the appropriate template. 

Please check out our [Contribution Guidelines](https://github.com/PTCInc/vuforia-engine/blob/master/CONTRIBUTING.md) for issue requirements. 

Thank you,
