### ISSUE TITLE
New Digital Eyewear Unity sample app - build issue on Hololens

### ISSUE THREAD

**Issue by alamboley** [PTCInc/vuforia-engine#137]
**Summarize the bug:**
When building the samples for HoloLens, I've this error: `BuildFailedException: Vuforia Digital Eyewear Sample requires the Hand Tracking feature to be enabled`. The Visual Studio template isn't output. I tried to add *Hand Interaction Profile* in *Enabled Interaction Profiles* but without luck.

**Affected Vuforia Engine version:**
E.g. v10.24.

**Comment by ptc-thesbyro** [comment]
Hi,

I was able to reproduce your issue. Please be patient while we investigate. 

Thank you,

**Comment by ptc-thesbyro** [comment]
Hi,

Can you try enabling the _Hand _Tracking _ feature in the **OpenXR Feature Groups** for UWP and see if it will build?

**Comment by alamboley** [comment]
Hello! Thank you for the input, it worked fine:
![image](https://github.com/PTCInc/vuforia-engine/assets/687978/33d13e06-d072-427d-ab7e-704e89110927)
