### ISSUE TITLE
There is no proper steps mentioned to prevent a continuously running vuCloudImageTargetObserverRegisterHandlers

### ISSUE THREAD

**Issue by hiren-addweb** [PTCInc/vuforia-engine#141]
[Troubleshooting Discrepant Reco Counts](https://developer.vuforia.com/library/cloud-recognition/counting-cloud-recognition-events#troubleshooting-discrepant-reco-counts)

**Elaborate on your feedback or issue**
I wanted to stop tracking cloud queries when the object from the cloud is detected and cached locally. But didn't find a clear guide on how to do it. My entire setup is completely based on the Vuforia sample and I have integrated cloud reco functionality in it.

**Describe the solution you'd like**
If there is a reference code sample or guide on stopping vuEngineRegisterStateHandler after the callback detects the cloud image target. it would be very helpful for the user and save unnecessary cloud recognition calls.

**Describe possible alternatives you've considered**
Alternatively, if someone can guide me based on my code, that will also be best for me for now.

**Additional Context**
- I am building app in android using vuforia native SDK

**Comment by hiren-addweb** [comment]
@ptc-thesbyro if you can guide me on this, it would be really helpful

**Comment by ptc-thesbyro** [comment]
Hi @hiren-addweb,

I think you can deactivate the Cloud Image Target Observer to stop Vuforia Engine from searching for new targets. 

You can for example do this after you create an Image Target with `vuEngineCreateImageTargetObserverFromCloudObservation`. Then if successful, call `vuObserverDeactivate(observer)`
Then the handler won't get called anymore and any Image Targets created from the search results continue to work but have to be destroyed independently. 

Hope it helps,

**Comment by hiren-addweb** [comment]
But in that case, if I shift my camera focus to another target image and want to run a query how it can be done? if you can guide me about that.

**Comment by hiren-addweb** [comment]
```
        VuCloudImageTargetCreationError creationError;
        if (vuEngineCreateCloudImageTargetObserver(mEngine, &mObjectObserver, &cloudImageTargetConfig, &creationError) != VU_SUCCESS){
            // handle observer creation errors
            switch (creationError){
                case VU_CLOUD_IMAGE_TARGET_CREATION_ERROR_NO_NETWORK_CONNECTION:
                    // handle the "NO NETWORK" error
                    return  false;
                    break;
            }
        }
        eventHandler = reinterpret_cast<void (*)(
                const VuObservationList *, void *)>(&recoEventHandler);
        AppController *clientdata = this;
        vuCloudImageTargetObserverRegisterHandlers(mObjectObserver, *eventHandler, AppController::queryErrorHandler, clientdata);
```

this is how I currently use observer...

**Comment by hiren-addweb** [comment]
@ptc-thesbyro When I call "vuObserverDeactivate(observer)" it stops tracking objects altogether. I'm not sure why. If you could provide a proper example or guidance for implementing it with best practices, it would be very helpful for me.

**Comment by hiren-addweb** [comment]
update:

I managed to deactivateObserver using the following code:
`vuObserverDeactivate(clientData->mCloudImageTargetObserver);`

Now I need to reactivate the observer if the target is different from the current. ( meaning my focus is now on another image, I wanted to detect.) Regarding that below are a couple of questions in my mind that I need help with.
- How can I manage to do that?
-  If I detect the same image again how do I get metadata of that particular image will it count as another reco or is there any other way to do it?

For a single object, it is working fine. **Thanks for this valuable insight and suggestion**.

**Comment by ptc-thesbyro** [comment]
Hi @hiren-addweb, 

Let's slow down a little. This GitHub issue tracker and tags are for giving feedback, reporting bugs and issues, requesting features, and asking for documentation improvements. I feel we're getting sidetracked from the topic on this thread, which was stopping Engine from searching for new results.

To get help with debugging code, I recommend using StackOverflow with the tag [Vuforia]. 

Now, to your latest questions.
_If I shift my camera focus to another target image and want to run a query how it can be done?_ - Well, you shouldn't deactivate the Cloud Image Target Observer if you actually want to continue getting results on new images. 
_How can I manage to do that?_ - Keep your [Cloud Image Target Observer](https://developer.vuforia.com/library/sites/default/files/references/native/group__CloudImageTargetObserverGroup.html#gaf9c18e97d42a4149ec18c12537c9389a) activated.
_if I detect the same image again how do I get metadata of that particular image will it count as another reco or is there any other way to do it?_ - If you detect cloud image A, move to cloud image B, get a successful query, and then move back again to A and detect it, that counts as three recos. 
Vuforia Engine caches the previous reco result. This means that querying cloud image A, moving away, and returning to cloud image A will not count as a reco. If you successfully query a new cloud image (B), it will replace cloud image A in the cache and counts as a reco.  

Let me know if that answers your questions.

I apologize for not being able to help with debugging your application code. 

Hope it helps,

**Comment by hiren-addweb** [comment]
Apologies for the numerous comments.

Lots of things are clear to me now... Just a few last things and I am all good.
- Is there any way in Vuforia to use a combination of cloud image and local db image target or something related?
- Are there any best practices I can follow to manage or reduce continuous queries or cache already detected images in my local db or something to reduce queries or any other optimization I can do to be cost-effective for cloud queries?

Sorry again for the lots of comments. Your insight and guidance on the matter helped me a lot.

Thank you for your insightful answer.

**Comment by ptc-thesbyro** [comment]
No apologies needed. I'm happy to hear that you are getting a better understanding from this exchange.

You can most certainly combine cloud image databases and local Image Target Databases. The only difference between the two is the creation of the Image Target Observer. One is when a certain image is detected that matches against your cloud database, and the other is by getting the targetName of an image stored in a local database. Both methods end up giving you an Image Target Observer. You can also track Image Targets simultaneously if that suits your use case.

I'm not sure what the best approach is here, and, unfortunately, we do not have documentation or API for such a specific use case that I know of. My best guess is that you would use the Vuforia Web Services to [update the target,](https://developer.vuforia.com/library/web-api/cloud-targets-web-services-api#update) setting the cloud image to inactive once it has been detected and made into an Image Target Observer. Though, this requires more work to integrate web requests in your application.

**Comment by hiren-addweb** [comment]
is there any method using which I can put my cloud dataset data into my local dataset once the image is detected? So that way the object detection performance will be faster compared to the cloud when the user scans that image again?

otherwise, I am all good.

**Comment by ptc-thesbyro** [comment]
You can look into creating the Image target Observer directly from the camera with [vuEngineCreateImageTargetObserverFromBufferConfig()](https://developer.vuforia.com/library/sites/default/files/references/native/group__ImageTargetObserverGroup.html#gaab5c168175375ee80e646067af68f532), or from a file: [Create image targets at runtime](https://developer.vuforia.com/library/objects/create-and-modify-targets-native). Then you will store the image in the local storage. I don't think there's a way to add cloud images to a local Image Target database. 

It also depend if you want faster image tracking in a single session or have the app remember which targets it already detected over multiple sessions. A single session should be fine since an Image Target Observer is already created for the image; the (re)-detection and tracking should be instantaneous. For resuming or re-launching a new session, we only support that partly: See [Continued AR experiences](https://developer.vuforia.com/library/environments/best-practices-continued-ar-experiences)

**Comment by hiren-addweb** [comment]
Thank you @ptc-thesbyro for your valuable guidance. The issue can be marked as closed or resolved.
