### ISSUE TITLE
Flash Mode added to ARCore v1.45

### ISSUE THREAD

**Issue by tsoen** [PTCInc/vuforia-engine#148]
**Summarize your feature feedback**
Hello,
As @ptc-pscheper  mentionned in https://github.com/google-ar/arcore-android-sdk/issues/153, it seems Google added Flash Mode to ARCore v1.45: https://github.com/google-ar/arcore-android-sdk/releases/tag/1.45.0

Is there a plan to update the ARCore version to make use of this change ?

**Describe your feature**

**Use-case description**
Be able to use flashlight with ARCore for dark environments.

**Business impact**

**Workaround**
No.

**Additional context**
Add any other context or screenshots about your feedback here.

**Comment by ptc-thesbyro** [comment]
Hi @tsoen, 

I can confirm we are looking into the latest ARCore version and the support for flash mode. I cannot say if or when the support will be released for Vuforia Engine. I'll keep you and this thread updated, once I know more.

**Comment by ptc-thesbyro** [comment]
With the 10.27.3 release, the Flash for Android devices running ARCore v1.45 or later is now supported. Check the [Working with Camera in Unity](https://developer.vuforia.com/library/platform-support/working-camera-unity#flash-torch) and [Camera API Overview for Native](https://developer.vuforia.com/library/platform-support/vuforia-engine-camera-api-overview#cameracontroller) for implementation steps.
