### ISSUE TITLE
Vuforia not start when using with arfoundation together.

### ISSUE THREAD

**Issue by Weimmer** [PTCInc/vuforia-engine#15]
**Summarize the bug:**
Setup projekt with Vuforia and ARFoundation, use the XR Origin, add a simple image target, it works fine in play model, but after built and install into my iPhone, the Vuforia did not start I use the debug tool and read the console. Without XR Origin, Vuforia works too.

**Observed problem**
The console only shows "vuforai initialized" but no "voforia started" as expected. Can not see the child object of image target.

**Expected result**
once the image target tracked, the child object will show up as it should to be.

**Reproducible steps**
1. add xr origin for ar, add image target
2. add vufuria behaviour and default initialization error handle component on maincamera
3. test on play model the object shows once the image traget tracked
4. bulid and install on my iPhone, nothing happens even the image target is in front of the camera

**Affected Vuforia Engine version:**
v10.14.4

**Affected platform:**
 - Workstation OS: Mac
 - Platform Unity
 - Platform version 2022.2.12f
 - AR Foundation 5.0.5

**Affected device:**
 - Name: iPhone 13 pro
 - OS: iOS 16.4

**Additional comments**
I did lots of debugs, almost sure that is something wrong when Vuforia and ARFoundation work together.

**Comment by Weimmer** [comment]
I think the reason why it works on play model is that the arfoundation would not start on play model.

**Comment by IgnatiusDeveloper** [comment]
I have the same issue on Android devices.

I can't get Vuforia and ARFoundation 5.0 to work together for Android in Unity. In a basic scene with no code, using only Vuforia, the Image Targets recognition works perfectly. When this same basic scene is under ARFoundation 5.0, in play mode in the editor, the scene works correctly and Vuforia's Image Targets work correctly. However, when I run it on an Android device, Vuforia doesn't recognize the target.

These error messages from Vuforia appear in logcat when I use the ARFoundation 5.0 scene in an Android device:

Error Unity Exception in callback: Object reference not set to an instance of an object.
Error Unity Vuforia.Utility.ExtensionMethods.DelegateHelper:InvokeDelegate(Delegate, Object[])
Error Unity Vuforia.Internal.Core.Engine:OnStart()
Error Unity Vuforia.Internal.Core.Engine:Start(Action)
Error Unity System.Reflection.RuntimeMethodInfo:Invoke(Object, BindingFlags, Binder, Object[], CultureInfo)
Error Unity System.Delegate:DynamicInvokeImpl(Object[])
Error Unity Vuforia.Utility.ExtensionMethods.DelegateHelper:InvokeDelegate(Delegate, Object[])
Error Unity Vuforia.Utility.ExtensionMethods.DelegateHelper:InvokeWithExceptionHandling(Action`1, T)
Error Unity Vuforia.Internal.Core.Engine:InitOnCameraReady()
Error Unity Vuforia.Internal.ARFoundation.<CheckAvailability>d__20:MoveNext()
Error Unity UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

**Comment by ptc-ddowning** [comment]
Thank you for the reports. I've reverted the observations provided here for an internal review.

**Comment by ptc-ddowning** [comment]
Hello,

We believe we've identified the source of the issue and will look to release a fix in an upcoming release. In the meantime, here is a workaround:

- On the `XR Origin` GameObject, replace the `XR Origin` Component with an `AR Session Origin` (ignore the deprecation message)
- In the new component, set the `Camera Offset` GameObject as the `Camera Floor Offset Object`, the `Main Camera` as the `Camera GameObject` , and the `Tracking Origin Mode` to `Device`

**Comment by IgnatiusDeveloper** [comment]
Ok! The temporary solution worked for me. I will wait for the new release.

**Comment by ptc-ddowning** [comment]
This fix for this issue will be part of our upcoming Engine 10.16 release.

Thank you.

**Comment by yosun** [comment]
Is there official VisionOS support from vuforia

**Comment by yosun** [comment]
Tried adding latest vuforia to Unity 2022.3.18f PolySpatial 1.0.3 - could not build 

```
Library/PackageCache/com.ptc.vuforia.engine@e5885903f78d/Vuforia/Scripts/Internal/ARFoundationIntegration/ARFoundationFacade.cs(14,15): error CS0234: The type or namespace name 'ARFoundation' does not exist in the namespace 'Vuforia' (are you missing an assembly reference?)
```

**Comment by ptc-pscheper** [comment]
@yosun Please create a separate bug report and supported device request for the questions above. Thank you!

**Comment by ptc-epassaro** [comment]
Hi @yosun, we unfortunately don't have a sample project for ARFoundation + Vuforia. Also, the support for ARFoundation is now deprecated and will be removed in a future release of Vuforia.

In the meantime, if you haven't tried it yet, I would highly recommend you to try using the latest version of Vuforia: 10.25.4.
Some changes were made in the latest releases that might help with your issue.

If you try that, please let us know how it goes.

**Comment by yosun** [comment]
why is ARFoundation deprecated - it's a crucial part to integrating with ARKit/ARCore in (modern versions of) Unity 

Older versions of Unity do not build for iOS/Android versions on modern phones.
