### ISSUE TITLE
Area Target NO_POSE -- NOT_OBSERVED after Unity App on iOS is opened after it was paused (in background)

### ISSUE THREAD

**Issue by MaxShtok** [PTCInc/vuforia-engine#150]
**Summarize the bug:**
Area Target doesn't work after the iOS Unity App is re-opened after being paused, in background. According to Xcode debugging Vuforia stops and starts properly, but the target is lost and couldn't be observed. 

Target status: 1506hometests NO_POSE -- NOT_OBSERVED
DefaultObserverEventHandler:OnObserverStatusChanged(ObserverBehaviour, TargetStatus)
System.Reflection.RuntimeMethodInfo:Invoke(Object, BindingFlags, Binder, Object[], CultureInfo)
System.Delegate:DynamicInvokeImpl(Object[])
Vuforia.Utility.ExtensionMethods.DelegateHelper:InvokeDelegate(Delegate, Object[])
Vuforia.Utility.ExtensionMethods.DelegateHelper:InvokeWithExceptionHandling(Action`2, T1, T2)
Vuforia.Internal.Utility.ExtensionMethods.IEnumerableExtensionMethods:ForEach(IEnumerable`1, Action`1)
Vuforia.Internal.Observers.AObserver:Deactivate()
VuforiaPauseResume:OnApplicationPause(Boolean)

**Observed problem**
No augmentations after re-opening the app. It needs to be quit and re-started. 

**Expected result**
Augmentations appear normally after putting the App to pause and re-opening.

**Other observations**
Model Target works OK in same scenario. 

**Affected Vuforia Engine version:**
E.g. v10.12.3.

**Affected platform:**
 - iOS

**Affected device:**
 - iPhone 14 pro

**Comment by ptc-emaggio** [comment]
Hi @MaxShtok, thanks for the report. On iOS the behavior of the ARKit device tracker is different than on other platforms and this might affect the ability of AreaTargets to work properly on app resume. The following document outlines the behavior across different platforms https://developer.vuforia.com/library/environments/best-practices-continued-ar-experiences. For your case if the device tracker pose status stays as RELOCALIZING for more than a few seconds after resume you should try to reset the device tracker.

**Comment by ptc-thesbyro** [comment]
Due to inactivity, this issue will be closed. Feel free to reopen it again if you still have the issue.
