### ISSUE TITLE
Area Target Generator Can't open E57 file

### ISSUE THREAD

**Issue by OopsAngela** [PTCInc/vuforia-engine#152]
**Summarize your feature feedback**
The program has been imported with the E57 file, as shown in the figure, but an error occurs after clicking OK without giving a reason.
![image](https://github.com/user-attachments/assets/f6813c4a-273f-4281-b16b-135fad3de453)

![image](https://github.com/user-attachments/assets/f518cceb-b500-40f4-8537-ef3200994fe4)

**Comment by ptc-emaggio** [comment]
@OopsAngela thanks for the report,

Would it be possible to share the e57 you are trying to process? Also, which version of ATG are you using?

**Comment by OopsAngela** [comment]
> @OopsAngela thanks for the report, 谢谢你的报道，
> 
> Would it be possible to share the e57 you are trying to process? Also, which version of ATG are you using?是否可以分享你正在处理的e57 ?另外，你使用的是哪个版本的ATG ?
@ptc-emaggio 
thanks , reply ! I want to upload file, but it exceeds GitHub's upload limit（file:50MB）. Is there another way to provide it to you? Also, I am using the latest official ATG (10.25.4).

**Comment by ptc-emaggio** [comment]
@OopsAngela could you please use a service like WeTransfer or Dropbox and share the by email vuforia-feedback@ptc.com

**Comment by OopsAngela** [comment]
@ptc-emaggio hi, I have sent it to the email address you provided via WeTransfer. Please check your inbox.

**Comment by ptc-emaggio** [comment]
Thanks @OopsAngela I got your file and I was able to reproduce the issue with importing your E57 file. We will look into why the ATG tool is not able to import the generated 3dt file. Still, please note that the target generation was successful and a valid dataset `color.xml` and `color.dat` files should be available in the "Location" folder you selected

**Comment by OopsAngela** [comment]
@ptc-emaggio emmm..? Do you mean that you need the color.xml and color.dat files from the E57 file?

**Comment by ptc-emaggio** [comment]
@OopsAngela, what I meant is that the tool successfully generated the AreaTarget, which you can use in your app if you like.

**Comment by OopsAngela** [comment]
@ptc-emaggio Sorry, I found that through ATG I only received a 3dt file. I need to export it to Unity3D and use resources related to AreaTarget. I don't understand what you mentioned about being able to use it. Additionally, no, I did not use the scanning device mentioned in the official documentation; I used other spatial scanning devices. Will the issue with ATG be resolved, or do I need to use a device officially supported to obtain the E57 file?Thank you again for your reply.

**Comment by ptc-emaggio** [comment]
@OopsAngela your output folder should alread include the `*.unitypackage` file (despite the failure). This is all you need to use with Unity as described here https://developer.vuforia.com/library/develop-area-targets/area-targets-unity

**Comment by ptc-mhavlena** [comment]
@OopsAngela to get the required output (unitypackage) when the viewer is unable to read the 3dt model, one needs to press the "Generate" button instead of the "Import" button on the E57 Data dialog. As @ptc-emaggio said, import from a scan taken by an unsupported device will most likely not yield a fully functional target, though.

**Comment by OopsAngela** [comment]
@ptc-emaggio I understand the process of creating an area target. Currently, my E57 file cannot be opened by ATG, so I am unable to reach the step of outputting the Unity package

**Comment by OopsAngela** [comment]
@ptc-mhavlena Additionally, as you mentioned, E57 files are correctly usable, but ATG fails to open them because it does not support the device. In future versions of ATG, could the restrictions be relaxed to allow more E57 files to be used? This would enable users to check the completeness and usability of area target data in the 3DT preview and decide whether to proceed with Unity development. Furthermore, it would be great if Vuforia Area Target could support more MR glasses devices, as Hololens2's performance is currently not very impressive

**Comment by OopsAngela** [comment]
@ptc-emaggio  Additionally, as you mentioned, E57 files are correctly usable, but ATG fails to open them because it does not support the device. In future versions of ATG, could the restrictions be relaxed to allow more E57 files to be used? This would enable users to check the completeness and usability of area target data in the 3DT preview and decide whether to proceed with Unity development. Furthermore, it would be great if Vuforia Area Target could support more MR glasses devices, as Hololens2's performance is currently not very impressive

**Comment by OopsAngela** [comment]
@ptc-mhavlena I am currently unable to convert the E57 file into a 3DT file, so I cannot proceed to the output stage.

**Comment by ptc-emaggio** [comment]
@OopsAngela the following steps work for me with the E57 you provided:

1. Select the E57 file in ATG Data dialog
2. In the same data Dialog select a valid Location folder 
3. Click Generate ( you will get the 3dt error message, please ignore it)
4. Close ATG
5. Navigate to the Location folder you selected at step 2

The Location folder should contain several files including the Unity package you need to import in Unity

**Comment by OopsAngela** [comment]
@ptc-emaggio Thank you for your patient response. Finally, I hope Vuforia will soon support more MR glasses.
