### ISSUE TITLE
Tracking offset on HoloLens 2 for runtime generated image targets

### ISSUE THREAD

**Issue by daniel1v** [PTCInc/vuforia-engine#157]
**Summarize the bug:**

After upgrading from 10.22.5 to 10.25.4 runtime generated image targets are tracked with rotational and positional offset on HoloLens 2.

**Observed problem**

I have an app which does not include any image targets in the scene, at startup. Image targets are loaded at runtime, within the OnVuforiaInitialized callback from a device database, similarly to the code examples in the vuforia documentation. The app used to work for several years and several vuforia versions.

Recently I upgraded Vuforia from 10.22.5 to 10.25.4. After the upgrade, everything worked fine in Unity Editor Play Mode, when using the Webcam. Running the app on the device (HoloLens 2) the image target tracking suffers from a large rotational and positional offset. The offset seems to depend on where the app was started.

For Image targets that are present in the scene at app startup, everything works fine. The issue only occurs, when there is no image target in the scene at startup and the target is loaded from device database at runtime. 

Downgrading to 10.22.5 solved the issue for the moment.

**Expected result**
The tracking should work like before the upgrade to 10.25.4.

**Reproducible steps**

- Create a project and configure for HoloLens 2
- Add MRTK XR Rig
- Add Vuforia Behaviour to Main Camera
- Do *NOT* include any trackables in the scene
- Add a script, which loads an image target at runtime and attaches a visual game object to the target
- Check if app works in Unity Player Mode
- Compile for HoloLens 2
- Start on Device and try to track the image target

**Affected Vuforia Engine version:**
10.25.4

**Affected platform:**

 - Windows 10
 - Unity 2022.3.45f1

**Affected device:**

 - Microsoft HoloLens 2

**Screenshots / Video Recordings**

-

**Affected database**
vuforia mars image database

**Device or platform logs**

-

**Workaround**

Downgrade to 10.22.5

**Comment by ptc-epassaro** [comment]
Hi @daniel1v, thank you for the detailed report.
Just for completeness, which version of MRTK did you set up your project with? Are you using OpenXR or Windows Mixed Reality?
Also, one last thing: do you see the same issue if you create an ImageTarget at runtime in the Digital Eyewear sample?

**Comment by daniel1v** [comment]
Hello @ptc-epassaro, I am using MRTK3 with OpenXR.

I did not try that explicitely with the digital eyewear sample. I tried it with my app and with a minimal example, as described above. Both apps work with 10.22.5 and do not work with 10.25.4.

Would it bring additional value, if I also try it with the Eyewear Sample?

**Comment by ptc-epassaro** [comment]
Thank you for the additional information. If you haven't tried with the sample, then there's no need to do it now. I will look into this and will update this thread.

Thanks again for reporting this!

**Comment by ptc-epassaro** [comment]
Hi @daniel1v, I'm not able to reproduce the issue. I tried by creating the target during OnVuforiaStarted, then I added a button to the scene to create the target on demand. In both cases the augmentations were displayed exactly on the target.

Could you please share the script you're using to create the ImageTarget and the augmentation?

Also, can you tell us which OS Build of Windows do you have installed on your device and which Target SDK Version + Visual Studio version you are building the project with?

**Comment by daniel1v** [comment]
@ptc-epassaro thank you for your quick response.

A short update from my side: I followed your hint and used the Digital Eyewear sample. I copied my scenes and assets into the Digital Eyewear sample and got it to work with 10.25.4. I do not know, what is causingt the issue inside my project, but it seems to be a setting at project level or a package. I definitely have to take a deeper look at this. I am closing the issue, as it doesn't seem to be a Vuforia issue, although it came up after upgrading the package.

Do you have any suggestions for me, how to find out, what is causing the issue?

Also: It seems that the tracking is less stable when making fast movements. Could this be related to the changes that were under the hood?
