### ISSUE TITLE
MRTK3 Support

### ISSUE THREAD

**Issue by HaiKonofanDesu** [PTCInc/vuforia-engine#16]
**Summarize your feature feedback**
Compability with MRTK3

**Describe your feature**
Currently Vuforia is not compatible with MRTK3. You can import the Project and remove the Errors but one problem still exists:
When adding the Vuforia Behaviour script to the Main Camera in the MRTK XR Rig the Guide View is not visible. Probably due to clipping limited to 0.01 and the GuideViewRenderer spawing at 0/0/0. Moving the Z to something like 0.1 manually makes it visible but A) Way to small B) I see 2 GuideViews then (one per eye). Only when I then also update the scale to 10 I can see the overlay but then the Tracking does not work.

I think MRTK3 has a lot of cool new features that are important for some of our future use cases so compability with it would be appreciated, specially as it should not be that much work? Maybe I just set up something wrong (since the docs are Outdated) and that is the only problem. A quick verify would help a lot

**Use-case description**
We want to add Object Tracking to our MRTK3 Application and thought Vuforia would fit the best.

**Business impact**
Easier Object Tracking to highlight specific parts of a machine

**Workaround**
We are currently trying tracking with QR Codes to place the model, but so far no success.

**Additional context**
[My old Error Report](https://github.com/PTCInc/vuforia-engine/issues/12)

**Comment by HaiKonofanDesu** [comment]
Just did a little bit more digging
Is there any proper MRTK 2 Guide for Vuforia? In your Example in the AssetStore the Vuforia Behavior Script is never used and instead you use the ModelTargetsManager but so far I don't fully understand how everything works there. Maybe I can get it to work with MRTK3 that way

**Comment by HaiKonofanDesu** [comment]
@ptc-ddowning yes and it's the Problem I Just described. Just the process of using the Vuforia Behavior Script which does not work sadly and is not used in the AssetStore example.

Also the "VuforiaAdditiveSceneLoader.cs" Script does not exist which is the one that gets mentioned with MRTK.

**Comment by ptc-ddowning** [comment]
Here is some additional feedback:

1. The issue with the HoloLens sample is that 2D Guideviews are not shown correctly. This is a known issue, and our documentation needs to be updated - will open a ticket to get this done. For HoloLens, our recommendation is to use [3D Guide Views](https://library.vuforia.com/model-targets/model-target-guide-view#guide-view) as shown in the sample. 
2. As previously mentioned, there is no official support of MRTK3. Despite Engine not officially supporting MRTK3, and it currently being offered in-preview, we don't think there is any reason why it would not work with Engine out-of-the-box.

**Comment by ptc-pscheper** [comment]
This issue is closed due to inactivity. Feel free to re-open or create a new bug report in the future.
