### ISSUE TITLE
Whether to support Windows AR, publish the project as Windows side exe, continue to call the camera to identify objects after running the project, in addition to the release platform is different, the other are the same as on Android

### ISSUE THREAD

**Issue by longgnc** [PTCInc/vuforia-engine#163]
**Summarize your feature feedback**
A clear and concise summary of what your feature feedback is. 

**Describe your feature**
A detailed description of your specific feature request. 

**Use-case description**
Please provide a detailed description of the core problem being faced by you and how this new feature would address your needs.

**Business impact**
What value and impact would this bring you if this feature would be realized?

**Workaround**
Is there currently a workaround for you?

**Additional context**
Add any other context or screenshots about your feedback here.

**Comment by ptc-thesbyro** [comment]
@niefun, 

Please recreate your issue. Currently, it is not following the guidelines we have set up. We can only help you if you fill out the details listed in one of the templates. See the [contributing guidelines](https://github.com/PTCInc/vuforia-engine/blob/1d42568da43bf850270fe9e17fbb511e349c95b7/CONTRIBUTING.md) for more information
