### ISSUE TITLE
Wrong_Color_Model when adding image target

### ISSUE THREAD

**Issue by axinailedit** [PTCInc/vuforia-engine#165]
**Summarize your feature feedback**
A clear and concise summary of what your feature feedback is. 
I have a png format image with RGB-16 bit color model sizing under 1mb, but it can't be added as an image target for "Wrong_Color_Model"

**Describe your feature**
A detailed description of your specific feature request. 

**Use-case description**
Please provide a detailed description of the core problem being faced by you and how this new feature would address your needs.
I read your Troubleshooting Errors from the Target Manager, which suggests my image should fit these standards:
Your image is in one of the supported formats, PNG or JPEG. Its width is minimum 320px.
Your image is either grayscale or RGB-24 bit. This means that 32-bit images with an alpha channel (RGB + Alpha) are not allowed.
Your image size does not exceed 2.25 MB.

does RGB-16 bit not fit the requirements?

**Business impact**
What value and impact would this bring you if this feature would be realized?

**Workaround**
Is there currently a workaround for you?

**Additional context**
Add any other context or screenshots about your feedback here.

**Comment by ptc-thesbyro** [comment]
Hi @axinailedit,

RGB-16 bit should work as well. I have to double-check with the experts, but I believe the RGB-24 bits is the bits per pixel as a minimum. So, even a 8-bits/channel should work.

The Wrong_Color_Model error could also mean that there's an alpha channel, which is when an element has a transparency or is opaque. If you're using Adobe Illustrator or Photoshop, make sure to not use the _Transparency_ and the _Smaller File (8-bit)_ in the export window.

**Comment by axinailedit** [comment]
Hi Thijs,

Thank you for replying! Turns out transparency is indeed the issue because
my image was initially hand-painted on Procreate lol. I converted the image
format to jpg and this time it goes very well.

Would not have thought of this without your help, thanks so much! Have a
wonderful day!

**Comment by ptc-thesbyro** [comment]
That's great to hear. 

Happy developing!
