### ISSUE TITLE
Unity app crashes when trying to stop Vuforia

### ISSUE THREAD

**Issue by Joao-G-Martins** [PTCInc/vuforia-engine#168]
I am developing an app that performs model tracking, and upon detection, I need to take a picture using the device's camera. For that, I wanted to stop Vuforia from performing the tracking, but the application crashes when I do that, using the: 

VuforiaBehaviour.Instance.enabled = false;

I followed the documentation and even some forums and GitHub issues to disable Vuforia, and this is the main line code for that purpose, but it is not working for me. I am using Vuforia 10.28.4. and Unity 2022.3.45f1.

It happens both on Unity Editor as well as with Hololens 2.

**Comment by ptc-epassaro** [comment]
Hi @Joao-G-Martins,

Your issue has been closed as it does not follow our contribution guidelines. To ensure effective and timely support, it is mandatory to follow the guidelines and use our provided templates when submitting a bug report or feature feedback. However, I encourage you to re-submit your report using the above bug report template and also include the crash log or the logs from Unity, if possible. Please check [this page](https://developer.vuforia.com/library/troubleshooting/troubleshooting-your-app#collect-logs) for more information on how to collect logs.

Please check out our [Contribution Guidelines](https://github.com/PTCInc/vuforia-engine/blob/master/CONTRIBUTING.md) for issue requirements.

Thank you,
