### ISSUE TITLE
Android SDK of Vuforia Engine doesn't come up with x86 build

### ISSUE THREAD

**Issue by chantlong** [PTCInc/vuforia-engine#18]
**Summarize the bug:**
I am using a 2019 Intel Macbook and I downloaded the Android Vuforia Engine SDK from here.
https://developer.vuforia.com/downloads/SDK

**Observed problem**
When I try to build the app I would get an error saying it cannot find `lib/x86/libVuforiaEngine.so` 
Looking inside the build/lib folder of the SDK, I don't see an x86 build, which prevents me from building the app.

**Expected result**
I expect there to be an x86 build to build an app

**Other observations**

**Reproducible steps**
1.
**Affected Vuforia Engine version:**
E.g. v10.12.3.

**Affected platform:**
 - 2019 Intel Mac
 - Android Studio Flamingo (latest)

**Comment by ptc-pscheper** [comment]
Hey there! Have you tried our native Android sample to reproduce the error?

**Comment by ptc-pscheper** [comment]
This issue is closed due to inactivity. Feel free to re-open or create a new bug report in the future.
