### ISSUE TITLE
vuCloudImageTargetObserverRegisterHandlers triggers only one time for scan same Image twice

### ISSUE THREAD

**Issue by SantoshKhandare1** [PTCInc/vuforia-engine#21]
**Summarize the bug:**
I used the native iOS vuforia sample app and integrated the cloud recognition API trough [link](https://library.vuforia.com/cloud-recognition/working-cloud-recognition). Everything is working fine. There is now a problem when vuCloudImageTargetObserverRegisterHandlers only triggers once for scan the same image twice but handlers are called successfully when you scan the image for the first time or switch to a different image scan. 

**Expected result**
Cloud recognition handlers should called every time when scanning same image multiple times. 

**Affected Vuforia Engine version:**
v10.15.3.

**Comment by ptc-pscheper** [comment]
Hey there! Could you share reproducible steps based on the native iOS sample + your integration of Cloud Recognition?

**Comment by SantoshKhandare1** [comment]
destroy the observer and re registers the VuCloudImageTargetObservationsHandler works for me.
