### ISSUE TITLE
Vuforia Camera Flash / Torch does not work on Android

### ISSUE THREAD

**Issue by yosun** [PTCInc/vuforia-engine#23]
**Summarize the bug:**
`VuforiaBehaviour.Instance.CameraDevice.SetFlash(true);` works on iOS but does not work on Android.

In addition, very low frame rates on mid-tier Samsung Galaxy phones, from the last year. 

**Observed problem**

Please test `VuforiaBehaviour.Instance.CameraDevice.SetFlash(true);` to make sure it works on Android.

**Expected result**

`VuforiaBehaviour.Instance.CameraDevice.SetFlash(true);` should turn on the device flashlight.

**Other observations**
Share any other observations that you made while experiencing the bug.

**Reproducible steps**

**Affected Vuforia Engine version:**
10.13.3

**Affected platform:**
 - Workstation OS: Mac
 - Unity 2022.2.7
 - Android

**Affected device:**
 - Samsung Galaxy 

**Screenshots / Video Recordings**
Share any screenshots or video recordings from the platform or device. You can also use the [Session Recorder](https://library.vuforia.com/platform-support/recording-and-playback).

**Affected database**
If applicable, share your database / dataset which is affected in the issue you're experiecing.

**Device or platform logs**
```Share any logs from the platform or device.```

**Workaround**
Is there currently a workaround that you're using?

**Additional comments**
Add any other details about the problem here.

**Comment by ptc-pscheper** [comment]
Hi there, sadly this is a limitation with ARCore and not Vuforia Engine. To use the flashlight / torch on Android with Engine you'd need to disable the use of ARCore. You can share your bug report and thoughts via Google's issue related to the missing flashlight functionality: https://github.com/google-ar/arcore-android-sdk/issues/153.

**Comment by josefgrunig** [comment]
The torch functionality has been added on ARCore 1.45 on the 15 of August 2024. 
https://github.com/google-ar/arcore-android-sdk/releases/tag/1.45.0

Any plans to add it to the Vuforia SDK? If yes, do you have a timeline for the release?

Thank you for the support,
Josef

**Comment by ptc-thesbyro** [comment]
Hi, 

Please see the currently open ticket: https://github.com/PTCInc/vuforia-engine/issues/148. It will be updated as soon as we have more information.

Thank you,
