### ISSUE TITLE
Not identifying multiple model targets simultaneously

### ISSUE THREAD

**Issue by jithu480** [PTCInc/vuforia-engine#26]
**Summarize the bug:**
Multiple model targets created using Advanced Model Target are not identified and tracked simultaneously. But identified individually one at a time.

**Observed problem**
I have 2 model targets (say model-A & model-B) created using Advanced Model Target inside a dataset. When i keep physical model of model-A in front of camera, Vuforia identifies it and when I take model-A away from the camera and brings model-B in front of the camera, Vuforia identifies it as model-B. But when i keep both models in front of the camera, Vuforia is identifying only one Model either model-A or model -B and each model targets are identified one at a time. But when I keep both targets at the same time in front of the camera, the system is identifying only one at a time.

**Expected result**
When both physical models are kept in front of the camera, Vuforia should identify both models and should track both models.

**Other observations**
I tried creating 2 model targets in separate dataset but still had the same problem. I tried models of different shape but the result was same. 

**Reproducible steps**
1. Create a dataset with 2 model targets created using advanced model target (360 degree).
2. Import the dataset into unity
3. Add 2 model targets in the scene in the inspector window.
4. Create 2 prefabs and map one to each model target(make prefab as a child)
5. Run on windows or deploy to android.

**Affected Vuforia Engine version:**
 v10.15.3.

**Affected platform:**
 - Workstation OS:  Window
 - Platform :Unity
 - Platform version : 2021.3.16f1

**Affected device:**
 - phone used : oneplus nord CE
 - OS:  Android 11 oxygen

**Screenshots / Video Recordings**
![model-A identified](https://github.com/PTCInc/vuforia-engine/assets/21969835/8aa4f8af-50d9-48db-a5d4-2b0379fe1531)
![model-B identified](https://github.com/PTCInc/vuforia-engine/assets/21969835/0319b1bb-cc2b-4a1f-a718-7acdefb574a1)

**Comment by ptc-ddowning** [comment]
Hello,

The Model Targets feature only supports the tracking of a single target at a time. This is unlike other features, like Image Targets, where multiple images can be tracked simultaneously.

I will work with the team to insure this well documented in our library.

Thanks.

**Comment by ptc-pscheper** [comment]
@jithu480 Feel free to share your [feature feedback](https://github.com/PTCInc/vuforia-engine/issues/new/choose) within the "New Issue" window to share your use-cases for this potential feature improvement.

![image](https://github.com/PTCInc/vuforia-engine/assets/88328882/d61f2c38-2170-4a26-be62-8d643bc236b9)
