### ISSUE TITLE
Sample project does not compile for Andriod

### ISSUE THREAD

**Issue by hokwangchoi** [PTCInc/vuforia-engine#27]
**Share which article or sample this is related to**
https://library.vuforia.com/getting-started/getting-started-vuforia-engine-android-development

**Elaborate on your feedback or issue**
I followed all the steps in the article in Windows environment and it does not compile at the running step.

**Describe the solution you'd like**
Please update the article according to the latest Engine version and make sure it works.

**Describe possible alternatives you've considered**
I am currently debugging it myself.

**Additional context**
Latest Vuforia Engine
https://developer.vuforia.com/downloads/sdk
Latest Sample
https://developer.vuforia.com/downloads/samples

**Comment by ptc-pscheper** [comment]
Hi there! The article is verified with the latest version of our SDK and should work. Can you share the logs of Android Studio?

**Comment by ptc-pscheper** [comment]
This issue is closed due to inactivity. Feel free to re-open or create a new bug report in the future.
