### ISSUE TITLE
Failed to Start Vuforia in Hololens2 on resuming Vuforia

### ISSUE THREAD

**Issue by smurugap59** [PTCInc/vuforia-engine#29]
**Summarize the bug:**
When we disable and re-enable using `VuforiaBehaviour.Instance.enabled` in Hololens 2, we get "Failed to Start Vuforia" error message and there is no callback as to why Vuforia failed to start. 

**Observed problem**
In our Hololens-2 app, we have 2 model targets, but we disable and re-enable only one model target based on the app logic. Sometimes, when we disable and re-enable a model target using `VuforiaBehavior.Instance.enabled`, we get "Failed to Start Vuforia" error message. We've noticed this happens more with v 10.13.3 than the previous version v10.6.3. We haven't used any other versions. 

`ERROR : Failed to start Vuforia
UnityEngine.Debug:LogError(Object)
Vuforia.Internal.Utility.UnityLogger:LogError(String)
Vuforia.Internal.Utility.Log:Error(String)
Vuforia.Internal.Core.Engine:Start(Action)
Vuforia.Internal.Core.Engine:Resume()
Vuforia.VuforiaBehaviour:OnEnable()
UnityEngine.Behaviour:set_enabled(Boolean)`

**Expected result**
Vuforia should start as usual. If an error occurs, a callback should be provided on why Vuforia failed to start so it can be handled gracefully. 

**Other observations**
We subscribe to all Vuforia events such as the following. None of these functions are evoked when Vuforia fails to start during the middle of the application.

`VuforiaApplication.Instance.OnVuforiaStarted += Instance_OnVuforiaStarted;
 VuforiaApplication.Instance.OnVuforiaInitialized += Instance_OnVuforiaInitialized;
 VuforiaApplication.Instance.OnVuforiaPaused += Instance_OnVuforiaPaused;
 VuforiaApplication.Instance.OnVuforiaStopped += Instance_OnVuforiaStopped;
 VuforiaApplication.Instance.OnVuforiaDeinitialized += Instance_OnVuforiaDeinitialized;`

**Reproducible steps**

**Affected Vuforia Engine version:**
v10.13.3 - (https://library.vuforia.com/release-notes/vuforia-engine-release-notes#vuforia-engine-v10-13-3)

**Affected platform:**
 - Workstation OS: Hololens 2
 - Platform: Unity
 - Platform version: Unity 2020.3.42

**Affected device:**
 - Name: Hololens-2
 - OS: Windows

**Screenshots / Video Recordings**

**Affected database**

**Device or platform logs**
`ERROR : Failed to start Vuforia
UnityEngine.Debug:LogError(Object)
Vuforia.Internal.Utility.UnityLogger:LogError(String)
Vuforia.Internal.Utility.Log:Error(String)
Vuforia.Internal.Core.Engine:Start(Action)
Vuforia.Internal.Core.Engine:Resume()
Vuforia.VuforiaBehaviour:OnEnable()
UnityEngine.Behaviour:set_enabled(Boolean)`

**Workaround**
To restart the app. 

**Additional comments**
It would be good to understand why Vuforia fails to start and if that error can be exposed to the app for it to be handled safely.

**Comment by ptc-ddowning** [comment]
Hello,

Can you better describe why you took this approach for switching between Model Targets? Typically, we would recommend either:

1. Creating a [trained Model Target](https://library.vuforia.com/model-targets/advanced-model-target-databases) device database with both objects
2. Use [Engine APIs](https://library.vuforia.com/unity-extension/create-and-load-targets-unity) to swap the Model Target device databases at runtime

Thanks.

**Comment by smurugap59** [comment]
1. We didn't want to create an advanced model target database as both objects we want to track are close to each other in the same environment and both targets can move from time-to-time in the same session. 
2. We didn't use Engine APIs directly. We have 2 game objects (each is a model target with model target behavior and default observer event handler scripts attached to them) in the scene and we enable/disable the game object that we want to track. The sequence is 

- VuforiaBehaviour.Instance.enabled = false
- SetActive (false) both game objects.
- Re-initialize Vuforia if it has not been initialized previously. 
- VuforiaBehaviour.Instance.enabled = true
- Set the right gameobject to be active.

We adopted this approach almost 2 years ago and it has been working well until recently.  With v10.13.3, we are getting Vuforia failed errors more now but it doesn't happen everytime either.

**Comment by ptc-pscheper** [comment]
Is the error event that you shared the only error? Would it be possible for you to share the full log files?

**Comment by smurugap59** [comment]
Yes. The error event that I shared above is the only error. We are still using 2020.3 Unity LTS version and have no plans to upgrade soon. I'll share a sample project next week mimicking the behavior that we have. If there is any other library version or workarounds that we can try - let me know.

**Comment by smurugap59** [comment]
@ptc-pscheper - Can you point me to the supported Unity versions for each Vuforia Engine release?

**Comment by ptc-pscheper** [comment]
Hi there, at the moment this is sadly not possible and older versions are shared case-by-case.

Feel free to reach out via vuforia-feedback@ptc.com with your Engine Developer Portal account and I'd be happy to help you out to see if this solves the error.  

I also highly recommend to create a feedback request via this same GitHub issue tracker for an archive feature. This can be done by creating a separate issue and selecting "Feature Feedback".

**Comment by ptc-pscheper** [comment]
This issue is closed due to inactivity. Feel free to re-open or create a new bug report in the future.
