### ISSUE TITLE
Vuforia Model Target not stereo correct on HoloLens 2

### ISSUE THREAD

**Issue by PriyanshJalan** [PTCInc/vuforia-engine#30]
**Summarize the bug:**
Model Target not stereo correct on HoloLens 2

**Observed problem**
Vuforia Model Target not appearing correctly as viewed from the eye perspective the HoloLens 2. This issue remains with the HoloLens 2 Unity sample as well.

**Expected result**
The rendering needs to take into account the distance between the camera and the display and render accordingly

**Other observations**
Share any other observations that you made while experiencing the bug.

**Affected Vuforia Engine version:**
10.15.4

**Affected platform:**
Unity 2021.3.15
Hololens 2
MRTK 2.8.3

**Screenshots / Video Recordings**
![IMG_1042](https://github.com/PTCInc/vuforia-engine/assets/28981026/00e47d13-8fb8-4cc9-b6fb-5b6bb0bb1343)
![IMG_1041](https://github.com/PTCInc/vuforia-engine/assets/28981026/96a18302-4c70-4051-b06c-3a0b3b4cbd98)

**Comment by ptc-pscheper** [comment]
Hi there, are you referring to the slight misalignment seen in the shared screenshots? 

![image](https://github.com/PTCInc/vuforia-engine/assets/88328882/79df1573-c367-470c-b4b7-0d457f636375)

**Comment by PriyanshJalan** [comment]
Hi
Yes I am talking about the misalignment. Would it be possible to fix that ?

**Comment by ptc-pscheper** [comment]
Thanks for confirming. My thoughts are:

- Some misalignment is expected using the Hololens 2. Could you quantity (by cm/mm) how bad the alignment is when you look through the display? The camera that you used to take the pictures might not represent the correct location of your eyes.
- Have you done a proper user eye calibration before running the app?
- What is the target scale within the Model Target Generator and does that match the physical size of the object?

Thank you.

**Comment by ptc-pscheper** [comment]
This issue is closed due to inactivity. Feel free to re-open or create a new bug report in the future.
