### ISSUE TITLE
Device Specific (Google pixel  6/Google pixel 7/Google pixel 7 pro) - Camera behavior is not correct

### ISSUE THREAD

**Issue by SpencerIO** [PTCInc/vuforia-engine#31]
**Summarize the bug:**
Device Specific (Google pixel  6/Google pixel 7/Google pixel 7 pro) - Camera behavior is not correct
stackoverflow [Android Vuforia camera rotation incorrect when Auto Rotation is enabled](https://stackoverflow.com/questions/76149291/android-vuforia-camera-rotation-incorrect-when-auto-rotation-is-enabled)

**Observed problem**
App starts in Portrait. Is set to landscape during app use. The ARCamera is show as rotated 90 degrees

**Expected result**
ARCamera would be shows as normal. Just like on other Android and iOS devices

**Reproducible steps**
1. Create app that starts in portrait
2. Rotate app to landscape before ARCamera is shown
3. Start ARCamera
4. View issue with 90 degree turned camera

**Affected Vuforia Engine version:**
v10.9.3

**Affected platform:**
 - Android v13
 - Unity 2020.3.41f1

**Affected device:**
 - Device Specific (Google pixel  6/Google pixel 7/Google pixel 7 pro)

**Comment by ptc-pscheper** [comment]
Hi there, as discussed via email, it is recommended to upgrade the Unity version to 2021.3 or above and see if that solves the issue. For now the issue is closed, but feel free to re-open at any time.
