### ISSUE TITLE
Override detection position feature does not allow to change guideview

### ISSUE THREAD

**Issue by riccardokhm** [PTCInc/vuforia-engine#35]
Dear Vuforia support,
I just ran into a tracking issue related to the possibility to override the detection position of a model target. I am not able to correctly change the guideview with the "override detection position" option on, while with deactivating it guideviews are correctly visualized and I can switch between them. Do you have any suggestion?

Vuforia Engine 10.15.4 
Unity Editor 2021.3.13f1
Windows 10
Development platform: Android

Thanks for your support!

**Comment by ptc-pscheper** [comment]
Hi there, sadly this doesn't comply with your contribution guidelines as you did not add any reproducible steps. Please create a new bug report using the format provided in the template. For this issue I am not sure why it doesn't work for you, turning that option on you need to provide your own detection position.

For more information on contribution guidelines, please find them here: https://github.com/PTCInc/vuforia-engine/blob/master/CONTRIBUTING.md

**Comment by riccardokhm** [comment]
Hi Patrick,
thanks for your reply. I will open a new bug report to discuss my issue.
Thanks again!
