### ISSUE TITLE
Entering playmode with "Domain Reload" disabled fails initialization.

### ISSUE THREAD

**Issue by TheXRMonk** [PTCInc/vuforia-engine#38]
**Summarize the bug:**
After updating from 10.13.3 to 10.15.4, we've noticed that vuforia fails to initialize in playmode. And our project runs with "reload domain" disabled under "Enter Play Mode Settings".

The only way to fix is to enable reload domain, enter and exit play mode to trigger a domain reload, and then hereafter we can disable "reload domain" in the settings again and it will work for a while. 
Haven't figured out what triggers the bug, since we have to do this "dance" once in a while. 

**Expected result**
Should not fail to initialize.

**Affected Vuforia Engine version:**
v10.15.4

**Affected platform:**
 - Workstation OS: Windows
 - Platform Unity
 - Platform version 2022.3.2f1

**Workaround**
See above;
```
The only way to fix is to enable reload domain, enter and exit play mode to trigger a domain reload, and then hereafter we can disable "reload domain" in the settings again and it will work for a while. 
Haven't figured out what triggers the bug, since we have to do this "dance" once in a while. 

```

**Comment by ptc-pscheper** [comment]
Hi there, which Unity version are you using?

**Comment by TheXRMonk** [comment]
> Hi there, which Unity version are you using? And is it possible to add reproducible steps? (Accidentally closed and reopened this case, sorry!)

Unity version is in report above (2022.3.2f1)

I don't know how to provoke it to appear.

But I just found another workaround by simply reimporting a script to force a domain reload.

**Comment by TheXRMonk** [comment]
I think closing unity and after reopening the first time entering play mode without domain reload will trigger the initialization error.

**Comment by ptc-pscheper** [comment]
I will create a new Unity project, add the older version of Vuforia to it, and update it to see if I can reproduce the error. Which play mode are you using, the webcam mode?

**Comment by TheXRMonk** [comment]
> I will create a new Unity project, add the older version of Vuforia to it, and update it to see if I can reproduce the error. Which play mode are you using, the webcam mode?

Yes, using Webcam.

**Comment by TheXRMonk** [comment]
> I will create a new Unity project, add the older version of Vuforia to it, and update it to see if I can reproduce the error. Which play mode are you using, the webcam mode?

I got some more info for you here;

- This happens consistently in all our developers environment.

- I noticed that when I get the bug in play mode, then do the "domain reload workaround dance" by reimporting a random script outside of playmode, it then dirties our scene (something needs to be saved). If I then enter playmode without saving, it works fine and Vuforia initializes. 
If I do save the scene however, I shortly get this progress bar;
![image](https://github.com/PTCInc/vuforia-engine/assets/54309738/4c806ea8-90b6-40aa-95b5-39bd9a83d1d4)
And then the bug reappears.

**Comment by TheXRMonk** [comment]
> Hi there, sadly I was not able to reproduce the issue. Can you setup a new project and try to reproduce the issue, while writing down the steps to reproduce? If the issue cannot be consistently reproduced there is no way to solve the issue. I tried to reproduce the issue but was unsure what your "Enter Play Mode Settings" are. The "Reload Domain" property should already be disabled by default.

Pretty sure it's not off by default. Our settings looks like this;
![image](https://github.com/PTCInc/vuforia-engine/assets/54309738/546de0f9-3b35-4685-b6ba-af7b4604fe54)
Maybe we can set up a call next week? I can reproduce this issue fairly easy.

**Comment by TheXRMonk** [comment]
> 
> Also it seems, when I create a new Unity project, the project starts with the "Reload Domain" property disabled:
> 
> ![image](https://user-images.githubusercontent.com/88328882/255206184-2f3e15ba-c505-48f8-9ff6-aa5a2f05d38d.png)
> 
> Could you disable "Enter Play Mode Options" completely and try to see if that solves the issue?

I just opened the sample project in a fresh 2022.3.2f1 project, and was able to reproduce the bug.

I simply just went into the settings and turned off reload domain while keeping scene reload off. Then entered playmode and got the same initialization error. This is definitely a bug in Vuforia 10.16.5+4097.

The "Enter Play Mode options" tickbox has to be enabled for unity to even consider the "Reload Domain" and "Reload Scene". Default behaviour is that unity does perform domain and scene reload when you don't check "enter playmode options". 

https://docs.unity3d.com/Manual/ConfigurableEnterPlayMode.html

Yes, if we enable "Reload Domain" it works fine again in our project.

**Comment by ptc-pscheper** [comment]
Hi there, I was able to reproduce the bug. The steps were:

1. Create a new Unity project (2022.3.5f1)
2. Add Vuforia Engine to the project
3. Remove Main Camera and Add ARCamera
4. Enable "Enter Play Mode Options" and "Reload Scene" while disabling "Reload Domain"
5. Start Play Mode
6. Stop Play Mode
7. Create a new C# script in the Project files
8. Start Play Mode
9. See Initialization error

Could you elaborate why you need this setting to be enabled for your project? It seems that when "Enter Play Mode Options" is turned off, the issue is not appearing. The workaround as well is to disable "Enter Play Mode Options".

**Comment by TheXRMonk** [comment]
Awesome!

> Could you elaborate why you need this setting to be enabled for your project? It seems that when "Enter Play Mode Options" is turned off, the issue is not appearing. The workaround as well is to disable "Enter Play Mode Options".

Simply because without domain reload we can enter playmode in less than a second, while with domain reload it takes around 30 seconds and will only get worse as a projects grow. 
_tldr: Iteration time_

**Comment by ptc-ddowning** [comment]
Hello @TheXRMonk,

The fix is targeted for our next commercial release (10.17), due in mid-August.

We appreciate your assistance and patience.

**Comment by ptc-pscheper** [comment]
Please note that v10.17 has been released and can be download via the Engine Developer Portal! Happy developing!
