### ISSUE TITLE
Trained model target does not show overlay properly in portrait mode on Android device  

### ISSUE THREAD

**Issue by akbartus** [PTCInc/vuforia-engine#4]
**Summarize the bug:**
Any overlay put on object target is rotated 90 degrees in portrait mode on Android device. When in landscape mode, the overlay shows properly.

**Observed problem**
Trained model target in portrait mode does not show properly in portrait mode (Unity > player settings) and any overlay is rotated 90 degrees on Android device. However when landscape mode is used in Unity, the overlay is properly displayed (without any rotation). 

**Expected result**
If model target is trained for portrait mode, it should show correctly in portrait mode on Android device.

**Other observations**
Inside unity's viewer, everything shows properly. I assume it is associated somehow with Vuforia's orientation code.

**Reproducible steps**
1. Train model target and make sure to select portrait mode. 
2. In player settings inside Unity make sure to select portrait only and android sdk version 8.0.
3. Publish as android apk app. 

**Affected Vuforia Engine version:**
Vuforia SDK v10.13.3.  

**Affected platform:**
 - Workstation OS: Windows 10
 - Platform: Unity
 - Platform version: 2021.3.13f1

**Affected device:**
 - Name: Samsung Galaxy
 - Model: A03s
 - OS: Android 12

- Name: Samsung
 - Model: J3 Orbit
 - OS: Android 9

**Screenshots / Video Recordings**
https://drive.google.com/file/d/1wrPhCh5weWfbz2WExz-vSke29SmuUQLU/view?usp=sharing Bug screenshot
https://drive.google.com/file/d/1cD1cDy2CCrlZf0eqTBj0oL95x6Gk7NeG/view?usp=sharing - Guide view with physical model
**Affected database**

**Device or platform logs**
-
**Workaround**
-

**Additional comments**
-

**Comment by akbartus** [comment]
**Small update:** With older version, Vuforia 10.3.2 there is no such a bug. However during my tests with versions . 10.5.5, 10.7.2, 10.9.3, 10.11.3 the same bug emerges. It appears that it was not addressed for quite some time.

**Comment by ptc-pscheper** [comment]
Hi there, thank you for the additional feedback. I will go through the issue and reproducible steps in the next working days.

**Comment by akbartus** [comment]
Hi! Is there any updated on the bug observed? Please feel free to write any questions related to the bug or if additional info is required.

**Comment by ptc-pscheper** [comment]
Apologies for the long wait. I will make sure this is looked at today or Monday. Thank you for understanding.

**Comment by ptc-pscheper** [comment]
Hi there, the issue cannot be reproduced. I don't see a rotated view of the target nor augmentation. Can you try to find another physical object and Model Target to see if the issue persists?

**Comment by ptc-pscheper** [comment]
This issue is closed due to inactivity. Feel free to re-open or create a new bug report in the future.
