### ISSUE TITLE
3DT File error and ATG UI crash

### ISSUE THREAD

**Issue by elliotmarsico** [PTCInc/vuforia-engine#41]
Unable to open 3DT file generated with ATG or generate target:
I am unable to generate a 3DT file for a specific property that is larger. (10.16.3 has not fixed this)
When attempting to generate a file that does successfully open the 3DT file, the ATGs UI goes entirely white from top to bottom. No headers, labels, or images of any kind.

Observed problem:
When opening the 3DT file generated by the matterpak, I receive a message saying the 3DT file is not compatible with this version (have tried with multiple different version from 10.10, 10.15, 10.16)

New to 10.16.3:
When the 3DT file is opened for a different property, the entire ATG goes white when attempting to generate the target.

Expected result:
The 3DT file is opened up in dollhouse view and the target can be generated.

Affected Vuforia Engine version:
Incompatible 3DT: 10.10, 10.15, 10.16
White Screen Crash: 10.16.3

Affected platform:
 - Workstation OS: Windows

**Screenshots / Video Recordings**
![image](https://github.com/PTCInc/vuforia-engine/assets/115429589/9c9c2062-ec2e-4c86-a146-5d0856069d70)

**Comment by ptc-ddowning** [comment]
Hello @elliotmarsico,

Would you be willing to share the 3DT file that is creating the problem? Having that will be important to an investigation.

Thank you.

**Comment by elliotmarsico** [comment]
Here is the link to the other property that causes the white screen crash in 10.16.3:

https://drive.google.com/file/d/1T4raX9sOAa8OpKBOKqZ6jWUYR0XNhFlq/view?usp=sharing

**Comment by elliotmarsico** [comment]
I would also like to add that these matterport scans were taken with the Matterport Pro3 camera. These issues have start arrising since we started using this.

Unsure if it is related to the camera, outdoor scanning feature, or the bigger size of the files.

**Comment by ptc-ddowning** [comment]
Hello @elliotmarsico,

Thank you for the artifact. I was able to successfully reproduce the "white screen" issue with ATG 10.16.3. I will open a ticket for investigation and provide relevant updates here.

We appreciate your patience in this matter.

Thanks, 
Vuforia Support

**Comment by elliotmarsico** [comment]
@ptc-ddowning I would like to post an update. We decided, to possibly work around the issue we are getting, to delete a number of the scans to make the file smaller. Now, we are able to generate the area target, but when importing the unity package into one of our projects, the property is imported without the mesh or any of the textures.

**Comment by elliotmarsico** [comment]
![image](https://github.com/PTCInc/vuforia-engine/assets/115429589/fbbe4ab7-e528-406b-89b3-356c27175143)

This error message is displayed when attempting to import the generated target file.

**Comment by ptc-ddowning** [comment]
@elliotmarsico thanks for the additional feedback. I have reverted it back to the team who is currently working on a fix.

**Comment by ptc-ddowning** [comment]
@elliotmarsico unfortunately, the fix for Windows ATG **will not** make it into our next release (SDK 10.17). A fix for MacOSX **will** be available in 10.17.

Additionally, we were unable to replicate the loading issue you [recently posted](https://github.com/PTCInc/vuforia-engine/issues/41#issuecomment-1668111411). We were able to load it on Windows machine using Engine 10.16.5 and Unity 2022.x. As the mesh has > 1000 textures, it does use quite a bit of resources.

**Comment by elliotmarsico** [comment]
Our project is currently Unity 2020.x which could be the issue.

Thank you for your help and responsiveness.

**Comment by ptc-ddowning** [comment]
@elliotmarsico thanks for the update. Good to hear that worked.

We do provide [guidance on compatibility](https://library.vuforia.com/platform-support/supported-versions) - just may not be obvious to find.
