### ISSUE TITLE
Run android build get black screen, after lock and unlock screen then camera works as expected.

### ISSUE THREAD

**Issue by Weimmer** [PTCInc/vuforia-engine#42]
**Summarize the bug:**
Import Vuforia and Image tracking asset, build for android, run the app on device, it get black screen, once I lock and unlock the screen then the black screen issue is gone, everything works fine.

**Observed problem**
Run the app on device, it get black screen, once I lock and unlock the screen then the black screen issue is gone, everything works fine.

**Expected result**
Run app and no black screen, the screen rendern the camera view.

**Reproducible steps**
1. Import Vuforia and Image tracking asset.
2. Run the app on device.
3. Black screen.
4. Lock and unlock the screen.
5. App works as expected.
6. 
**Affected Vuforia Engine version:**
v10.16.5

**Affected platform:**
 - Workstation OS: Windows 11
 - Platform Android
 - Platform version 2022.3.5f1

**Affected device:**
 - Name: Samsung 
 - Model: S7+
 - OS: Android 13

**Workaround**
Just lock and unlock the screen then works.

**Comment by ptc-pscheper** [comment]
Hi there, could you provide log files of your app? That could point us to the issue. Also it would be helpful if you can share the device model number. 

Please **note** that this device is not part of the [recommended device list](https://library.vuforia.com/platform-support/recommended-devices) and that support could be limited.

**Comment by Weimmer** [comment]
> Hi there, could you provide log files of your app? That could point us to the issue. Also it would be helpful if you can share the device model number.
> 
> Please **note** that this device is not part of the [recommended device list](https://library.vuforia.com/platform-support/recommended-devices) and that support could be limited.

Hi, I just got the Infos:

**the model number is: SM-T970
log the message: Skipped rendering frame because GfxDevice is in invalid state (device lost)**

hope this help.
best regards

**Comment by Weimmer** [comment]
https://forum.unity.com/threads/issue-with-android-skipped-rendering-frame-because-gfxdevice-is-in-invalid-state-device-lost.1449145/
I think the reason is here, in case someone has some issue, only remove the AR package will not solve the problem.
