### ISSUE TITLE
Vuforia 10.16.5 Shutdown device in Unity project

### ISSUE THREAD

**Issue by IProroIK** [PTCInc/vuforia-engine#43]
**Summarize the bug:**
Vuforia 10.16.5 Shutdown device in Unity project

**Observed problem**
When create a build for android device, and AR camera is enabled build shutdown after 5-10 seconds, tested in empty Unity project with only adding vumark from database, in Unity Editor all works fine

**Expected result**
App works normaly and scanning vumarks

**Other observations**
In 9.8.13 there isn`t such problem, all works good as expected

**Reproducible steps**
1. Create Unity project and Import Vuforia 10.16.5
2. Import database with vumark, create AR camera, and vumark object to scan, choose vumark to scan, create child object on Vumark GO to see it was scaned
3. Build app, and try to scan vumark
4. Crash without log error after 5-10 secods

**Affected Vuforia Engine version:**
E.g. v10.16.5.

**Affected platform:**
 - Workstation OS: Windows
 - Platform Unity
 - Platform version 2022.3.1f1 2022.2.1f1

**Affected device:**
 - Name: Sumsung Galaxy A71
 - Model: SM-A715FZSUSEK
 - OS: Android 13

**Affected database**
[If applicable, share your database / dataset which is affected in the issue you're experiecing.
](https://developer.vuforia.com/targetmanager/project/targets?projectId=adeb1fabadf542e58776bb838eeda4c4&av=false)

Additional comment
First problem was occured, on my working project when i update package from 9.8.13 to 10.16.5, then I test last version of vuforia in new empty project, and it crash too(

**Comment by ptc-pscheper** [comment]
Hi there, I'll try to reproduce the issue this week based on your reproducible steps and come back with any feedback. The Samsung Galaxy A71 is not a recommended device, but does support ARCore and therefor is expected to work. Please note however that because it's not recommended, if it's a hardware-specific issue, support might be limited. Thank you!

**Comment by ptc-pscheper** [comment]
I was not able to reproduce the issue, though I also don't have access to the same device. Can you check if there were really no logs available? If the app crashes after some seconds, there must be some logs. Thanks.

**Comment by IProroIK** [comment]
Logs was that procces is killed
Problem was with build architecture with mono it crash, with IL2CPP works fine, so the problem solved

**Comment by ptc-pscheper** [comment]
Great to hear. Happy weekend!
