### ISSUE TITLE
Vuforia in Unity does not support exporting to webgl?

### ISSUE THREAD

**Issue by crazyfish2020** [PTCInc/vuforia-engine#44]
Vuforia in Unity does not support exporting to webgl?
if ok，Is there a guided tutorial?？

**Comment by ptc-pscheper** [comment]
Thank you for reaching out. I noticed that your issue does not follow the required format outlined in our contribution guidelines. To ensure effective and timely support, it is mandatory to follow the guidelines and use our provided templates when submitting a bug report or feature feedback. These templates help us gather essential information to assist you properly.

**As your post does not adhere to the guidelines, I will close this thread.**

However, I encourage you to re-submit your question or report using the appropriate template. Here’s how:

- Review the Guidelines: Please revisit our [Contribution Guidelines](https://github.com/PTCInc/vuforia-engine/blob/master/CONTRIBUTING.md) for posting requirements.
- Use the Template: Select the relevant template when creating a new issue and answer the questions comprehensively.

Thank you.
