### ISSUE TITLE
Vuforia - Model Target Scan for an outdoor structure which is 30m by 30m

### ISSUE THREAD

**Issue by jaydevdave** [PTCInc/vuforia-engine#46]
**Summarize the bug:**
We are looking to build a model target AR experience for an outdoor structure which is 30m by 30m.
The structure has three similar layers one above the other with similar geometries throughout. It is having a height of a normal human being around 5.5 feet. We are generating the guide views with two approaches, one guide view with close view taking up the detailed textures of the structure but missing out the whole or full geometry. Second approach, where we generate a guide view with a far distance such that it includes the full structure in the view but does not include the detailed textures.

**Observed problem**
Result by scanning the structure at the real site -
In both the cases, when the guide view is matched with the real geometry, the structure gets detected by Vuforia but the augmentation model is not aligned properly. It shakes or changes the alignment with every move. Augmentation is not stable. What we believe is, Vuforia is understanding the scanned model, but missing some details which is leading to the misalignment.

The scanned structure used to generate the Model Target Database, has the bottom two layers of the structure and we are scanning it on a real structure which has three layers.

Results by scanning the structure in a 3D viewer or Model Target Generator -
When the structure (with two layers) opened in the Model Target Generator is scanned, we get accurate alignment of the augmentation structure. The problem only occurs when we scan a real site structure having three layers.

We generated guide views from the corner of the structure and tried scanning to give Vuforia as much information as possible but still didn't help.

**Expected result**
We should be able to augment the augmentation model at the right anchors, properly aligned and should not be shaking. It should stay stable.

**Other observations**

1. Actual Structure has three layers of similar geometries, and we have scanned only the first two layers in the scanned structure, and we are training Vuforia to identify a structure with two layers and then scanning it on a structure with three layers at the real site. Could this be an issue? (Because the same two layered scanned structure when scanned from MTG, augments the augmentation model at proper anchors)
2. Do we require Area Target Scan for a structure which is 30m by 30m? Is the model target not sufficient enough to scan such a huge structure? I don't think so. We are able to scan the similar structure which is a big one, but it has more details.
3. Do we need to scan a structure which has more details in terms of geometry?

**Reproducible steps**

**Affected Vuforia Engine version:**
E.g. v10.15.4.

**Affected platform:**
 - Workstation OS: [e.g. Windows]
 - Platform [e.g. Unity]
 - Platform version [e.g. 2021.3.16f1]

**Affected device:**
 - Name: [e.g. One Plus, Samsung Tablets]
 - Model: [e.g. One Plus 8]
 - OS: [e.g. Android 11]

**Screenshots / Video Recordings**
Share any screenshots or video recordings from the platform or device. You can also use the [Session Recorder]

**Affected database**

**Device or platform logs**

**Workaround**
No

**Additional comments**

**Comment by ptc-pscheper** [comment]
There should be enough visual distinctive features of the building in order for Model Targets to work but this case is very difficult to assess without information such as videos or photos. Also note that this is not a supported use-case of Model Targets.

**Comment by jaydevdave** [comment]
Hi Patrick Scheper, Is this the case of Area Target then?
