### ISSUE TITLE
Watermark appears with basic license and GroundPlanes - Vuforia  10.16.5 & Unity 2022.3.6

### ISSUE THREAD

**Issue by muckletone** [PTCInc/vuforia-engine#47]
**Summarize the bug:**
Using Unity 2022.3.6, and Vuforia 10.16.5 under a Basic Plan and a new license implementing Ground Planes the Watermark seen in the user view

**Observed problem**
Using Unity 2022.3.6, and Vuforia 10.16.5 under a Basic Plan and a new license implementing Ground Planes the Watermark seen in the user view. But when working in Unity in Run mode, the watermark is not displayed

**Expected result**
It is my understanding that use of the Basic Plan and Groundplanes will not impose the Watermark.

**Other observations**
Share any other observations that you made while experiencing the bug.

**Reproducible steps**
Normal Build and install processes without errors.

**Affected Vuforia Engine version:**
10.16.5

**Affected platform:**
 - Workstation OS: MacOS for iOS deployment
 - Platform: Unity, Apple Xcode, Android Studio]
 - Platform version: Unity 2022.3.6, Xcode 15

**Affected device:**
 - Name: Apple iPad and iPhone
 - Model: iPad 6th Gen , iPhone 13
 - OS: iPad: 15.6.1 , iPhone: 16.1

**Screenshots / Video Recordings**
Share any screenshots or video recordings from the platform or device. You can also use the [Session Recorder](https://library.vuforia.com/platform-support/recording-and-playback).

**Affected database**
If applicable, share your database / dataset which is affected in the issue you're experiecing.

**Device or platform logs**
```Share any logs from the platform or device.```

**Workaround**
Have not found one as of yet

**Additional comments**
None
![2023-08-21-08-06-38-660](https://github.com/PTCInc/vuforia-engine/assets/48600837/b5a752a1-f0c0-4a5b-93ae-f2e1e204c583)

**Comment by ptc-pscheper** [comment]
Hi there, can you share the first few digits / characters of the license UUID that is used in your app? Can you verify your reproducible steps and elaborate on them? Would be interested to know what objects you add to the scene for example. Thank you.

**Comment by muckletone** [comment]
Good morning and thank you for responding

The first few characters of the latest license which i am using are "AbpAWgj/////AAABma3PGkYnt0/"

And glad to elaborate.

Using the usual Build steps in Unity, i confirm the license is in place and all other build settings are good. Typically i run the app simulation in Unity, and there is no watermark. If everything is good i build. Then the build exports an Xcode project to a build folder. I open the Xcode project, go through the usual steps of making sure splash page images and icons are all i place and that the signing is set to automatic for all aspects. It builds successfully and installs on to iOS devices.

The app has 3D models of trees (this is to be a tool for arborists), which are loaded in the app. When the Groundplane is detected, the user taps the target location and which ever model that was previously selected by the user is instantiated at the GroundPlane location. This is a self-contained app in case the user is in the field and cannot get network coverage. So, i don't download a model from a remote network.

Hope this is helpful. I am a one-person developer, and am not nearly as skilled as the pros out there, so maybe i am doing something obviously wrong but i can't see it.

thanks much

**Comment by VicM** [comment]
I am also experiencing the same issue.

I have been developing apps with vuforia for the past 7 years, so to the issue reporter, there is nothing wrong with your setup.

My project using the simulator work with AR, no watermark, AR tracking working. When I build for Android, I installed the APK on the device, the app start the watermark shows and I have no AR tracking.

My app is only using image targets and ground plane too. The models are just simple industrial products with textures, materials.

Also hpoing a quick answer from Untiy on how to workaround this as this hinder development as is not possible to test on device as at least I don´t have any tracking.

**Comment by muckletone** [comment]
Hi all,

I noticed that 10.17.4 Vuforia Engine has been released. Do you suggest i update the engine and retest?

thanks

**Comment by ptc-pscheper** [comment]
Hi all, the new version might not have any affect. I tried to reproduce the issue with a basic license but could not reproduce. Can you verify when your license was created? Please note that older (~2021 and below) basic licenses have the behavior that they show the watermark inconsistently in newer versions of the SDK. I am still waiting for the team to check your license to see if I can reproduce it with your specific key.

**Comment by muckletone** [comment]
Thanks much for the reply. I will proceed to update to the latest engine in a duplicate of the project just to be safe and test this evening. The license i am using was created just a week or two ago, it seemed like a possible issue. My original license was generated in 2019, but the current one is 2023. Many thanks!

**Comment by muckletone** [comment]
Good morning PTC-Pscheper, just wanted to report, after making a copy of the project, i upgraded to Vuforia 10.17 but that had no impact on the issue i am experiencing. But wanted to make sure i did my part to inform you. Thanks for the help.

**Comment by VicM** [comment]
hi @muckletone , I have been working hard the last three days to identify the problem. I finally got a solution because for me is not enough to justify the "could not reproduce". It seems is a problem of the Vuforia package particularly when updating the AR engine. When starting on a fresh project all works ok, but once you upgrade vuforia somehow the vuforia package install corrupt something and the vuforia scripts (for example the ones associated to the camera or image targets) are not fully referencing to the actual Vuforia objects in the scene, although the AR functionaly works on the simulator on the device there is no AR tracking and watermark appears as no initialization is performed properly.

![v1](https://github.com/PTCInc/vuforia-engine/assets/5496260/2923b44a-7820-4736-be1b-583cd618a5a9)
![v2](https://github.com/PTCInc/vuforia-engine/assets/5496260/2c12d826-1853-4f50-a955-4efcda261a82)

The other problem i noticed produced by this corrupting is that despite a valid license is filled in the Vuforia configuration, the license gets deleted from time to time and you have to added it again.

**What I did is the following.**

On your project, comment any of your scripts referencing Vuforia and the AR functionlaity, this to avoid future compile issues in the next steps. Then go to the Unity package manager and search for the Vuforia package. Uninstall it and wait until finishes. If errors are shown in the console, comment any missing code lines necessary until no errors are shown in the console.

Manually find for any Vuforia file in the project (search for vuforia, ptc, etc), remove the folders or files, including your markers. Also make sure to remove the QCAR folder in your project root (you will need to delete it via finder or windows file explorer).

Now, close Unity. Preferably move your project to another route. Then open the Unity project again, after is fully loaded, open a new scene. Then import the Vuforia asset package and wait. Add the AR camera and a image target and see if the scripts are referenced, if so then build for your device and test.

This way I was able to fix this problem in an existent project and in a new one where i started to copy all my original projects until vuforia started to fail due to the upgrade.

On one of the projects I had to repeat the process three times, just try and see if that helps on your side.

**Comment by ptc-pscheper** [comment]
@muckletone that is strange. A legacy license (prior to 2021) can cause the watermark issue you're experiencing. Therefor it's advised to generate a new license for projects using Engine v10.x. Can you verify the issue you're experiencing is caused with a  10.x version and with the basic license created in 2023?

**Comment by ptc-pscheper** [comment]
@VicM It seems that you're experiencing another issue and I would advise to create a different bug report for your issue. Thank you.

**Comment by muckletone** [comment]
@VicM Thanks for all that work. I am not having that issue though, the scripts are there and don't have compile errors. Sure hope you can find a solution that doesn't demand that much of you to get it to work.

**Comment by muckletone** [comment]
@ptc-pscheper Hello Mr. Scheper, thanks for the response. My latest test was with 10.17.4 and a new license. But knowing i am the less experienced here, i noticed you said "generate a new license for projects using Engine v10.x". Currently i am just generating the license in my support portal. Is there a way to generate a license using the engine that i am not aware? Thanks much

**Comment by VicM** [comment]
> @muckletone that is strange. A legacy license (prior to 2021) can cause the watermark issue you're experiencing. Therefor it's advised to generate a new license for projects using Engine v10.x. Can you verify the issue you're experiencing is caused with a 10.x version and with the basic license created in 2023?

My license is from 2022, and that even happen with a new one I created a couple of days ago, it does not seems related to the license bug your refer prior 2021.

**Comment by ptc-pscheper** [comment]
I will reproduce the issue with Unity 2022.3.5f1 and v10.17.4 tomorrow and will share my results. Are you sure that there are no other (Premium) targets in the scene such as: Model Targets, Area Targets, and the Barcode Scanner?

**Comment by muckletone** [comment]
@ptc-pscheper Hello Mr. Scheper, yes, i can completely confirm i am not using any Model Targets, Area Targets or Barcode scanner. The only thing my app does is load a model, which is part of the app (ie, not downloaded from a remote server) and places it where ever the target is placed and the user taps the screen.

Thanks much for your help

**Comment by muckletone** [comment]
Hi again @ptc-pscheper If it is any help, here is the app in the Apple Store. Maybe there is something i am missing. I know it was working fine until we upgraded to 10.16

https://apps.apple.com/us/app/treescapedesign/id1505614111

Many thanks

**Comment by ptc-pscheper** [comment]
Hi there, I was unable to reproduce the issue sadly on my iPhone 5, nor on any Android device. Can you please create a new project with Unity 2022.3.x, add SDK v10.17, add a Ground Plane Stage + Plane Finder and check if the issue is persistent? Sorry that it takes longer than expected.

**Comment by muckletone** [comment]
@ptc-pscheper Hello Mr Scheper, thanks for all your efforts. I can do that this evening and get you a report by morning. Glad to do so, and no need for apologies, these things are always a bit of a challenge.

**Comment by muckletone** [comment]
@ptc-pscheper Hello again Mr Scheper, actually had a little time now, and i created the simple project per your instructions. It is built with Unity 2022.3.6 and Vuforia Engine 10.17.4. Nothing but what you outlined. Compiled just fine and loaded on my device, took a screencap, and i am still getting the watermark. See screencap below.

Thanks much.
![Screenshot 2023-08-31 at 10 45 18 AM](https://github.com/PTCInc/vuforia-engine/assets/48600837/3fc1a19e-ce70-44a9-9216-b5f132c66f63)

**Comment by ptc-pscheper** [comment]
Hi there, thank you for taking the time! I've asked internally our test engineering team to help out as I don't have the specific device available. We'll try to reproduce the issue on the iPhone 12.

**Comment by ptc-pscheper** [comment]
Hi there, we've tried to reproduce the issue but have not been able to. Please verify that your basic license is added in the Vuforia Configuration file. This was tested on an iPhone 12 (iOS 16.6).

**Comment by muckletone** [comment]
@ptc-pscheper  Hello, and sorry for the slow response, one of those mornings. Thank you for move this up to others. Yes, the test you asked was using my latest license was added to the project. That license was generated during the course of this inquiry. I have not deleted the old license, should i and could that some how contribute to the issue? Many thanks

**Comment by ptc-pscheper** [comment]
Would it be possible to zip up your test project and share it with me so I can reproduce it with your project?

**Comment by muckletone** [comment]
@ptc-pscheper Why of course, i will have that test project to you very shortly. Many thanks.

**Comment by muckletone** [comment]
@ptc-pscheper Question for you, this is about 1GB (which seems really large), not sure i can attach it here. Is there a better way to send you something this large?

**Comment by muckletone** [comment]
@ptc-pscheper Sorry, my bad, it is about 430mb, still large though. How would you like this delivered to you?

**Comment by ptc-ddowning** [comment]
Hello @muckletone,

We've had good experiences using [WeTransfer](https://wetransfer.com/). That would be my suggestion.

Thank you.

**Comment by muckletone** [comment]
@ptc-ddowning @ptc-pscheper Thanks, i don't have an account on that system yet, perhaps i can provide you a DropBox link, thanks

**Comment by muckletone** [comment]
@ptc-pscheper @ptc-ddowning Hello all, here is a Dropbox link to the zip package of the project

https://www.dropbox.com/scl/fo/v95xcvxrvoo1cb3e9boql/h?rlkey=h6lu0ackiqjiw5ofadc33wlnz&dl=0

**Comment by ptc-pscheper** [comment]
Any cloud storage provider is fine, so thanks! I've shared the project with our team to reproduce as soon as possible. Have a good start of your weekend!

**Comment by ptc-pscheper** [comment]
Hi there, with your specific project we've been able to reproduce the issue. We're currently very surprised and will do a technical deep dive in the project. This sadly will be taken over by our R&D team and will take some time. I'd suggest to try to change the Unity version, if supported, and possibly create a new project to see if the issue persists. Can you share your hardware specifications where you created your project?

**Comment by VicM** [comment]
I had the android working on the device after my fixes, but I now switched to iOS and again started the same problem on apple devices, a watermark appear in a scene in where i use image targets, no tracking is performed. I had another scene with ground plane that shows the vuforia watermark, however the plane tracking is performed and can place objects.

My license is valid, it was working on android just today.

In the xcode i see this logs:

2023-09-08 15:06:34.377128-0600 JC Augmented Reality[416:21853] INFO/AR(416) Creating ImageTargetObserver...\
2023-09-08 15:06:34.463934-0600 JC Augmented Reality[416:21853] ERROR/AR(416) Dataset Vuforia/JC.dat not valid with the used Vuforia license. Please check your license.\
2023-09-08 15:06:34.464125-0600 JC Augmented Reality[416:21853] ERROR/AR(416) Dataset Vuforia/JC.dat not loaded successfully.\
2023-09-08 15:06:34.464201-0600 JC Augmented Reality[416:21853] ERROR/AR(416) Failed to verify the signature of the Dataset Vuforia/JC.dat\
2023-09-08 15:06:34.466295-0600 JC Augmented Reality[416:21853] ERROR/AR(416) Failed to load database 'Vuforia/JC.xml'.\
2023-09-08 15:06:34.466474-0600 JC Augmented Reality[416:21853] ERROR/AR(416) Creating ImageTargetObserver...FAILED\
Exception in callback: Failed to create ImageTargetObserver: Make sure that a license key is provided in the Vuforia Configuration.\
Vuforia.Utility.ExtensionMethods.DelegateHelper:InvokeDelegate(Delegate, Object[])\

It seems like the database i am using is detected as invalid for the license hoever is the same license used for android, i just switched platforms in unity.

**Comment by ptc-pscheper** [comment]
@VicM please create another bug report in order for us to support you. Thank you.

**Comment by VicM** [comment]
@ptc-pscheper here is the related bug #54. Any helps is appreciated.

**Comment by ptc-pscheper** [comment]
@muckletone We've identified that the issue is related to the "Managed Stripping Level" which is set to "High". Please set it to another value and it should result into no watermark shown. We'll fix this issue in a future release.

Please also note once again that since you shared your license above in full, and in your project, that it's advised to cancel your license and generate a new one via the License Manager as it might be compromised.

**Comment by ptc-pmessenger** [comment]
@muckletone a stripping level of "low" should also work fine.

**Comment by ptc-pscheper** [comment]
No problem! Thank you for finding the bug. Feel free to share your findings, and if so, close the issue.

**Comment by muckletone** [comment]
@ptc-pscheper Hello and huge thanks. Deleted the previous license, created new, did a fresh build after making the recommended build change, and the watermark is no longer showing. This is huge for me, a solo developer. REALLY, appreciate all the efforts. Pass the thanks along. I will get the case closed in just a few minutes.

**Comment by muckletone** [comment]
The Vuforia Team was very helpful and patient as they worked through a stubborn issue. And i have ever reason to believe it will be addressed in future releases. Was a very good experience.
