### ISSUE TITLE
The virtual buttons are being triggered by themselves when I lower the camera and point it at a 45 degree angle relative to the image, when it is somewhat closer to the image.

### ISSUE THREAD

**Issue by MonchoXR** [PTCInc/vuforia-engine#48]
**Summarize the bug:**
A clear and concise summary of the issue.

**Observed problem**
Describe the observed problem as detailed as possible.

**Expected result**

**Other observations**
Share any other observations that you made while experiencing the bug.

**Reproducible steps**

**Affected Vuforia Engine version:**
E.g. v10.12.3.

**Affected platform:**
 - Workstation OS: [e.g. Windows, Mac]
 - Platform [e.g. Unity, Apple Xcode, Android Studio]
 - Platform version [e.g. 2021.3.1f1]

**Affected device:**
 - Name: [e.g. Google Pixel 6a]
 - Model: [e.g. GX7AS]
 - OS: [e.g. Android 12]

**Screenshots / Video Recordings**
Share any screenshots or video recordings from the platform or device. You can also use the [Session Recorder](https://library.vuforia.com/platform-support/recording-and-playback).

**Affected database**
If applicable, share your database / dataset which is affected in the issue you're experiecing.

**Device or platform logs**
```Share any logs from the platform or device.```

**Workaround**
Is there currently a workaround that you're using?

**Additional comments**
Add any other details about the problem here.

**Comment by ptc-pscheper** [comment]
Thank you for reaching out. I noticed that your issue does not follow the required format outlined in our contribution guidelines. To ensure effective and timely support, it is mandatory to follow the guidelines and use our provided templates when submitting a bug report or feature feedback. These templates help us gather essential information to assist you properly.

**As your post does not adhere to the guidelines, I will close this thread.**

However, I encourage you to re-submit your question or report using the appropriate template. Here’s how:

- Review the Guidelines: Please revisit our [Contribution Guidelines](https://github.com/PTCInc/vuforia-engine/blob/master/CONTRIBUTING.md) for posting requirements.
- Use the Template: Select the relevant template when creating a new issue and answer the questions comprehensively.

Thank you.
