### ISSUE TITLE
Try to get camera image failed with official sample code in Unity

### ISSUE THREAD

**Issue by CharlieJiang** [PTCInc/vuforia-engine#5]
**Share which article or sample this is related to**
[working-camera-unity](https://library.vuforia.com/platform-support/working-camera-unity)

**Elaborate on your feedback or issue**
image.CopyToTexture(mTexture, true) keeps get errors when run in Unity, the error message is "Exception in callback: bool UnityEngine.Texture2D.Reinitialize(int,int,UnityEngine.TextureFormat,bool)" . and in Android device, the error message is "Exception in callback: Error: called non-existent method System.Boolean UnityEngine.Texture2D::Reinitialize(System.Int32,System.Int32,UnityEngine.TextureFormat,System.Boolean)"

**Affected Vuforia Engine version:**
Vuforia SDK v10.13.3.

**Affected platform:**

Workstation OS: Windows 10
Platform: Unity
Platform version : 2020.3.44f1c1

**Affected device:**

Name: HuaWei nova5

Model: SEA-AL00

OS: HarmonyOS 2.0.0

**Comment by ptc-pscheper** [comment]
Can you share reproducible steps for this issue? I was not able to reproduce your issue. I followed the documentation, added the code sample, created a "RawImage" GameObject and attached it to the "Raw Image" variable of the code sample in the inspector which resulted into the camera feed being shown within the image object.

**Comment by CharlieJiang** [comment]
I followed this steps :
![image](https://user-images.githubusercontent.com/5109850/222870397-6a71aad9-7001-424b-9e8a-c538a941e955.png)
but still get errors:
![image](https://user-images.githubusercontent.com/5109850/222870429-0e92b0b8-3e66-48ba-9676-9cc92de414fa.png)

**Comment by ptc-pscheper** [comment]
Hi there, can you try the same steps with Unity 2021.3.0 or above?

**Comment by ptc-pscheper** [comment]
This ticket is closed due to inactivity. Feel free to open the ticket if the recommendation to try to upgrade the Unity version does not work. Thank you!
