### ISSUE TITLE
Merge multiple Session Recordings in a single file

### ISSUE THREAD

**Issue by devrandomzero** [PTCInc/vuforia-engine#51]
**Summarize your feature feedback**
Merge multiple session recordings in a single file

**Describe your feature**
I hope this is the right section to ask this, in ourt test case we have multiple targets in the real world that are immovable (like pictures and statues) and rather far away from each other, so as you can imagine it's not quite feasable to make a single session recording as instructed in the documentation ([link](https://library.vuforia.com/platform-support/recording-and-playback#session-recorder-in-unity)) without creating a large mp4 file.
So, is it possible to  merge into a single video file a collection of all the recodings made for every single target?
I've tried with a couple of free utilities (without re-encording) but the newly created video is not recognized and played by Vuforia in the Unity Editor in play mode.

**Use-case description**
Read above

**Business impact**
Faster testing and development

**Workaround**
Work with a single session recording for every target to test the correct detection when offsite

**Additional context**
None

Thank you for your help

**Comment by ptc-pscheper** [comment]
Hi there, thank you for sharing your feedback and will share your feedback internally. As you realized this use-case is not supported as of today. I have two workarounds however:

- You create single small session recordings and hot-swap these during runtime in play mode. You can set the recording path of the play mode configuration via our the [API](https://library.vuforia.com/sites/default/files/references/unity/classVuforia_1_1VuforiaConfiguration_1_1PlayModeConfiguration.html#a2477e469e566312e53f0b7c2051bdb33). Please **note** that when switching the path you must first _de-init_ and after _init_ Vuforia.
- You could develop a custom driver that would allow you to cycle over multiple files automatically. The [File Driver sample](https://library.vuforia.com/platform-support/building-and-using-file-driver-sample#use-the-file-driver-in%C2%A0unity) acts as a blueprint how to play a file from a session recording. This is however **not** available for play mode.

I hope that helps a little.

**Comment by devrandomzero** [comment]
Thank you!
