### ISSUE TITLE
Vuforia 10.17 Ground Planes not working with Galaxy S23

### ISSUE THREAD

**Issue by ribowcott** [PTCInc/vuforia-engine#52]
**Summarize the bug:**
Ground planes fail to initialise on both Galaxy S23 & S22. 

**Observed problem**
App launches as expected but no plane is found and therefore unable to place content. All other aspects of the app appear to be functioning as normal. I have tested an iOS version of the app and this works as expected. 

**Expected result**
Vuforia engine should identify a flat surface and offer up the plane indicator, allowing the user to place the AR content.

**Reproducible steps**
1. Create an Engine scene with Ground plane as the tracking type
2. Build apk and run on Samsung Device.

**Affected Vuforia Engine version:**
E.g. v10.17.4.

**Affected platform:**
 - Unity 2022.2.18
 - Android Studio 2023

**Affected device:**
 - S23 & S22
- SM-S911B/DS
 - OS: Android 13

**Comment by ptc-pscheper** [comment]
Hi there, can you share the SDK version and try to reproduce the issue by building the [Core Samples](https://assetstore.unity.com/packages/templates/packs/vuforia-core-samples-99026) to your device and see if a plane can be detected?

**Comment by ribowcott** [comment]
> Hi there, can you share the SDK version and try to reproduce the issue by building the [Core Samples](https://assetstore.unity.com/packages/templates/packs/vuforia-core-samples-99026) to your device and see if a plane can be detected?

I actually managed to fix the issue by updating Unity to 2022.3.8f1 which is the recommended version in the Vuforia [Documentation](https://library.vuforia.com/platform-support/supported-versions)

**Comment by ptc-pscheper** [comment]
Great to hear, thank you for verifying.
