### ISSUE TITLE
MissingMethodException with Vuforia10.17 and Unity2021

### ISSUE THREAD

**Issue by violet0330** [PTCInc/vuforia-engine#53]
**Summarize the bug:**
MissingMethodException: Method not found: int UnityEngine.SceneManagement.SceneManager.get_loadedSceneCount() 
after import Vuforia 10.17 to Unity 2021

**Observed problem**
After import Vuforia10.17 package into Unity, the throwing Exception 'MissingMethodException: Method not found: int UnityEngine.SceneManagement.SceneManager.get_loadedSceneCount()' will pop out. No matter I add the AR camera or not, it all cames. Also, if I just remove the Vuforia packet in package manager, this problem will not exist. 

**Expected result**
is there any way to solve it?

**Other observations**
I just tried the old version 10.13, and this exception won't exist.

**Reproducible steps**
just import the Vuforia Engine, then run the current no bug scene without adding new things.

**Affected Vuforia Engine version:**
10.17 (newest

**Affected platform:**
Unity Editor

**Affected device:**
Windows

**Device or platform logs**
MissingMethodException: Method not found: int UnityEngine.SceneManagement.SceneManager.get_loadedSceneCount()

**Comment by ptc-pscheper** [comment]
Please note that the minimum Unity version for **SDK v10.17.4 was updated to be Unity 2022.3.x and above**. Please update to 2022.3.x to see if the issue still persists.
