### ISSUE TITLE
Watermark started to appear on iOS with no tracking, on android it was working ok.

### ISSUE THREAD

**Issue by VicM** [PTCInc/vuforia-engine#54]
**Summarize the bug:**
Watermark started to appear on iOS with no tracking, on android it was working ok.

**Observed problem**

On Android my project was working, both image targets and ground plane. When switching the project to iOS with no other changes my image target scene shows a watermark and tracking is not working, the image targets are not recorgnized.
In my ground plane scene the watermark is shown but ground detection is working.

And yes, the license is in place in the vuforia configuration.

In the xcode console I see these messages:

2023-09-08 15:06:34.377128-0600 JC Augmented Reality[416:21853] INFO/AR(416) Creating ImageTargetObserver...
2023-09-08 15:06:34.463934-0600 JC Augmented Reality[416:21853] ERROR/AR(416) Dataset Vuforia/JC.dat not valid with the used Vuforia license. Please check your license.
2023-09-08 15:06:34.464125-0600 JC Augmented Reality[416:21853] ERROR/AR(416) Dataset Vuforia/JC.dat not loaded successfully.
2023-09-08 15:06:34.464201-0600 JC Augmented Reality[416:21853] ERROR/AR(416) Failed to verify the signature of the Dataset Vuforia/JC.dat
2023-09-08 15:06:34.466295-0600 JC Augmented Reality[416:21853] ERROR/AR(416) Failed to load database 'Vuforia/JC.xml'.
2023-09-08 15:06:34.466474-0600 JC Augmented Reality[416:21853] ERROR/AR(416) Creating ImageTargetObserver...FAILED
Exception in callback: Failed to create ImageTargetObserver: Make sure that a license key is provided in the Vuforia Configuration.
Vuforia.Utility.ExtensionMethods.DelegateHelper:InvokeDelegate(Delegate, Object[])\

It seems like the database i am using is detected as invalid for the license in use, however is the same license used for android that was working minutes ago, i just switched platforms in unity to test my project on iOS.

Any help you can provide is appreciated, I have a project delivery milestone this week and hope this can be resolved quickly. Thanks!

My platform, sdk, settings:
Unity 2022.3.7f1
Vuforia: 10.17.4
Vuforia basic license: created on june 2022, also happen with a testing license created on agosto 2023.

**Comment by ptc-pscheper** [comment]
Hi there, as with the other case we identified that the issue was related to the "Managed Stripping Level" setting set to "High". Can you verify this is the case with you?

![image](https://github.com/PTCInc/vuforia-engine/assets/88328882/c55d81e2-fe32-4a63-b498-0ddf373666ad)

**Comment by VicM** [comment]
Hello, in my case stripping engine code is set to medium.

Thanks!

**Comment by VicM** [comment]
I confirm that stripping engine code set to medium breaks Vuforia, the watermark appears and no tracking is performed on the image targets. When returning to low all came back working ok.

Is there any way I can make Vuforia work with stripping set to medium? I am using another plugin in unity which require at least medium to remove unused iOS capabilities of the library.

Any possible solutions even if that involves myself in the need to modify or copy files manually, I have to present a functional demo on Thursday so any possible workaround will be very much appreaciated. thanks!

**Comment by ptc-pscheper** [comment]
Hi there, I'll discuss with the team, but the current verified workaround is to set the "Managed Stripping Level" to either "Minimal" or "Low".

**Comment by ptc-pscheper** [comment]
Sadly the feedback is that the bug currently shows when selecting "Medium" or anything higher. This will be fixed in a future release.
