### ISSUE TITLE
pinch-to-zoom on smartphones in front of a large object for Vuforia AR camera

### ISSUE THREAD

**Issue by schories** [PTCInc/vuforia-engine#55]
As kindly suggested I ask the questions here, original question is on SO - https://stackoverflow.com/questions/77097943/pinch-to-zoom-on-smartphones-in-front-of-a-large-object-for-vuforia-ar-camera 
_______________________________

Situation:

AR detection works best, when the object is fully visible within the camera view.

Expected result:

So when users are in front of larger AR objects, e.g. big vending machines, they expect to use pinch-to-zoom to zoom out - instead of walking backwards.

Last official information I found is from 2020:

https://developer.vuforia.com/comment/74482   Back then, pinch-to-zoom was not supported.

Is it supported now?

Thank you!

**Comment by ptc-pscheper** [comment]
@schories Are you asking the ability to increase and decrease the scale of the expected target when using Model Targets? For example, if this viking lander was larger than in the picture, the customer could adjust the size of the expected white outline?

![image](https://github.com/PTCInc/vuforia-engine/assets/88328882/8be22681-22a4-498e-8220-e8e37a970938)

**Comment by schories** [comment]
@ptc-pscheper 

Thank you for your fast and kind reply, Patrick.

- advanced model target of a large physical machine in public spaces, e.g. as this DHL Packstation, 

![image](https://github.com/PTCInc/vuforia-engine/assets/847938/91791f74-473b-4b9d-9e40-c9c347d8cb64)

- advanced view, 360 degree dome (although 180 degree would be sufficient most of the time)

- no white outline (as in your screenshot) used at all

The advanced model target of such a large physical item is recognized best, when 
- either the person holding the smartphone steps back 5m from the object, to have the full object view 
- or the person "zooms out", by using the pinch-to-zoom feature like in every normal camera/photo app of every modern smartphone camera; thus most of the time avoiding walking back and possibly falling or hitting other persons - because of being focused watching the camera view on the phone.. ;-) )

Hope I was able to convey the issue better this time.

Thank you very much

Alexander

**Comment by ptc-pscheper** [comment]
Hi Alexander! Have you tried to work with the "Constrained Angle Range and Target Extent" feature which should help define and recognize a Model Target from a limited angle or close-up views? https://library.vuforia.com/model-targets/advanced-views#constrained-angle-range-and-target-extent

It might be what you're looking for without having to step back or "zoom out", as you know, this is not a feature (as of today) within the SDK.

**Comment by schories** [comment]
Hi Patrick,

not exactly what the users wish for, but we certainly will have a good test with the above feature and get back to you after. 

Thank you once again,

Alexander

**Comment by ptc-pscheper** [comment]
Hi Alex! This feature would allow users to not having to step back or zoom out, so I'd be sure that this can be what your users might need, even though not asking for.

**Comment by schories** [comment]
Hi Patrick,

we meanwhile tested "Constrained Angle Range and Target Extent" feature. It surely allows to select a smaller viewpoint - but not a larger one like zoom-out. 

We need to zoom-out in order to have the full object view - like the photographer of the above photo - to have the model target recognize the object. For partial recognition of such a low feature object currently only smaller image targets (e.g. stickers) were successful.

We understand the constraints better now, also thanks to https://stackoverflow.com/questions/77097943/pinch-to-zoom-on-smartphones-in-front-of-a-large-object-for-vuforia-ar-camera - and will continue without zoom.

Thank you once again!
