### ISSUE TITLE
Support for the Universal Render Pipeline (URP) for Vuforia Model Target Generator

### ISSUE THREAD

**Issue by schories** [PTCInc/vuforia-engine#56]
As kindly suggested I ask the question here also, original question is on SO - https://stackoverflow.com/questions/77016275/pink-material-problem-with-vuforia-model-target-and-unity-universal-render-pip
__________________________________________________________________________________

Process:

We use the Vuforia Model Target Generator to import CAD model data, train and then export the trained model as a unitypackage. This unitypackage is then imported into Unity with Vuforia Engine.

Current result:

The unitypackage created by Vuforia Model Target Generator currently builds assets for Unity's Built-In Render Pipeline (BRP) only.

Importing this unitypackage into Universal Render Pipeline (URP) based projects leads to issues. So does conversion from Built-in into URP. E.g. as documented here: https://stackoverflow.com/questions/77016275/pink-material-problem-with-vuforia-model-target-and-unity-universal-render-pip

Expected result:

Export offers the possibilty to export to either BRP or/and URP.

Reasons to use URP:
- Unity recommends the URP for new projects with a wide platform support (https://docs.unity3d.com/Manual/render-pipelines-overview.html). 
- The URP also offers new features (https://docs.unity3d.com/Manual/render-pipelines-feature-comparison.html) 
- Many new assets, esp. new shaders, in the Unity Asset Store are made for URP only.
- Most importantly the URP in general offers better performance in comparison to BRP on most devices.

Thank you!

**Comment by ptc-pscheper** [comment]
Hi there, it has been a while but I wanted to thank you for the feedback provided which has been considered by the product team. We're looking into possibly releasing a new version of the SDK and tools to allow support for URP in the future.

**Comment by ptc-pscheper** [comment]
@schories Vuforia Engine v10.21 and above now support the Unity Universal Render Pipeline (URP)! This means that all Vuforia Engine built-in shaders, resources, and prefabs are now URP-compatible for URP projects.

**Comment by schories** [comment]
@ptc-pscheper  Excellent, thank you all very much! 👍

**Comment by Zhou04191919** [comment]
Whether compatibility with a particular UPR version is required, some shaders in my 10.22.5 Import URP project are reporting errors

**Comment by ptc-thesbyro** [comment]
@Zhou04191919 please open a new bug-report using the provided template and describe what versions you're using, what shaders are reporting errors, and steps to reproduce.

Thank you,

**Comment by RyanRei** [comment]
Hey there! Im using the latest version of vuforia from the project manager and whenever I import it in the projects folder, it switches back to No pipeline selected, and switching back the pipeline creates bugs with materials and so
