### ISSUE TITLE
NO_POSE--NOT_OBSERVED

### ISSUE THREAD

**Issue by MalayJoshi254** [PTCInc/vuforia-engine#57]
**Summary**
I recently upgraded Vuforia package from 10.16.5 to 10.17.4 due to which i also upgraded my unity from 2022.1.17f1 to 2022.3.9f1 I have used 10 image target for each 10 3D models. Now when I click play in unity all my models disappears and it throws a log error with NO POSE NOT OBSERVED

**Observed problem**
I think issue is with Default Event Handler script. When I remove that script and click on play button in unity, all the model appears in scene as well as simulation part. however, if I add default event handler. again, same error appears no pose not observed and all my model disappears from scene as well as simulation.

**Expected result**
My app was working fine with Vuforia 10.16.5 and unity 2022.17.1f1. i am getting error only after upgrading the SDK.

**Other observations**
I checked with other unity version 2022.3.5/2022.3.8 but faced same issue.

**Affected Vuforia Engine version:**
v10.17.4

**Affected platform:**
 - Workstation OS: [Windows]
 - Platform [Unity]
 - Platform version [2022.3.9/8/5f1]

**Screenshots / Video Recordings**
![after play button](https://github.com/PTCInc/vuforia-engine/assets/70467161/2de3380d-00cf-4272-b720-9261b0ebd13c)
![before play button](https://github.com/PTCInc/vuforia-engine/assets/70467161/412c5a33-244c-41c0-9862-4d1ada2bf152)

**Device or platform logs**
Target status: GRAPES NO_POSE -- NOT_OBSERVED
UnityEngine.Debug:Log (object)
DefaultObserverEventHandler:OnObserverStatusChanged (Vuforia.ObserverBehaviour,Vuforia.TargetStatus) (at ./Library/PackageCache/com.ptc.vuforia.engine@6ce555af7186/Vuforia/Scripts/DefaultObserverEventHandler.cs:94)
DefaultObserverEventHandler:Start () (at ./Library/PackageCache/com.ptc.vuforia.engine@6ce555af7186/Vuforia/Scripts/DefaultObserverEventHandler.cs:63)

**Workaround**
Is there currently a workaround that you're using?

**Additional comments**
Please share old Vuforia SDK 10.16.5 or Default event handler updated script.

**Comment by ptc-pscheper** [comment]
Thank you for reaching out. I noticed that your issue does not follow the required format outlined in our contribution guidelines. To ensure effective and timely support, it is mandatory to follow the guidelines and use our provided templates when submitting a bug report or feature feedback. These templates help us gather essential information to assist you properly.

**As your post does not adhere to the guidelines, I will close this thread.**

However, I encourage you to re-submit your question or report using the appropriate template. It's specifically important in your case to provide reproducible steps. Without reproducible steps we won't be able to support. Here’s how:

- Review the Guidelines: Please revisit our [Contribution Guidelines](https://github.com/PTCInc/vuforia-engine/blob/master/CONTRIBUTING.md) for posting requirements.

Thank you.
