### ISSUE TITLE
Microsoft Surface Pro 9 and SENSOR_FUSION provider

### ISSUE THREAD

**Issue by Softelectro** [PTCInc/vuforia-engine#60]
Hello,

We want to migrate an Unity ARFoundation (ARCore) to an Windows tablet such as Microsoft Surface Pro 9.
After several test, we can't have the SENSOR_FUSION provider only VISION_ONLY. And this mode isn't enough to have a good tracking.

We are aware that Surface pro 9 isn't in compatible device list but the Surface pro 8 is near the end of life. So, we want to use the latest one for our development and futur deployment.

We read that needed a calibration to unlock the SENSOR_FUSION provider. How can we proceed to do this step?

Unity 2020.3 LTS
Vuforia 10.16.3
Microsoft Surface Pro 9 for Business (S7B-00023) with Windows 10

Thanks in advance for your reply

**Comment by ptc-ddowning** [comment]
Hello,

Unfortunately, unlike iOS (ARKit) and Android (ARCore), UWP does not provide a platform CV solution for device pose tracking. Thus, in order for UWP devices to support Engine's SENSOR_FUSION provider, they must be 'hand calibrated' by our team. The SP8 had been previously calibrated, but the SP9 has yet to be done.

Can you please clarify what you mean by "_the Surface pro 8 is near the end of life_"? We find this puzzling as the SP8 was released in Fall 2021, and will be supported until 2027 (per the attached screen grab).

<img width="734" alt="UWP_SP8_EOL" src="https://github.com/PTCInc/vuforia-engine/assets/15641233/b21dd2ff-7196-49a0-b894-3391b4585a8a">

Thanks,
Vuforia Support

**Comment by Softelectro** [comment]
Hello,
Thanks for your reply.

> Can you please clarify what you mean by "the Surface pro 8 is near the end of life"?

By end of life, I meant that it is difficult to purchase the SP8 in official store. And can be more complicated when the deployment time will come.

> in order for UWP devices to support Engine's SENSOR_FUSION provider, they must be 'hand calibrated' by our team. 

Is the calibration of the SP9 is in your roadmap?

Thanks,

**Comment by ptc-ddowning** [comment]
Hello,

Thank you for the response. Although we currently do not support SENSOR_FUSION on the SP9, we periodically review our UWP device support coverage based upon usage. Thus, Engine's SENSOR_FUSION support for the SP9 may change in the future.

Thanks,
Vuforia Support

**Comment by Softelectro** [comment]
Hello,

What kind of info can we provided to Vuforia/PTC to increase the probability to adding the SP9's calibration in a near future in your roadmap?
Thanks.

**Comment by ptc-pscheper** [comment]
Hi there, there's an elaborated process to add a device to the [Recommended Devices](https://library.vuforia.com/platform-support/recommended-devices) list of devices for Vuforia Engine. We've made sure to note your feedback, but it would be helpful to share why this device is important for your use-cases apart from the SP8 being difficult to obtain. 

Additionally, if you're on a paid plan, it would be helpful to share additional information via vuforia-feedback@ptc.com, linking this thread, which can be added to the feedback we regularly review.
