### ISSUE TITLE
Can't buy premium license

### ISSUE THREAD

**Issue by kajetaneyvi** [PTCInc/vuforia-engine#61]
**Summarize the bug:**
I created an AR app in unity using vuforia model target. I want to buy premium license to remove watermark.

**Observed problem**
I tried contacting sales team for one month no with no success. Nobody answears our calls, email or contact forms.

**Expected result**
I expect someone to contact me and discuss what license do I need for my purpose and how much does it cost.

**Other observations**
It is not possible to get any information. Even online chat on webpage is not working.

**Reproducible steps**
1. Go to 'https://www.ptc.com/en/contact-us'
2. Fill the form
3. Click on 'Submit'
4. Wait forever for contact
5. Be disappointed

**Affected Vuforia Engine version:**
ALL

**Affected platform:**
 ALL

**Affected device:**
 ALL

**Additional comments**
Please contact us. Our deadline is coming soon.

**Comment by ptc-ddowning** [comment]
Thanks for the report, and apologies for the inconvenience. I've forwarded your information to the sales team - hopefully they will get in touch with you soon.

If in the future you (or others) have a similar issue, please feel free to email vuforia-feedback@ptc.com with your contact information.

-Vuforia Support
