### ISSUE TITLE
[AR] Failed to create ModelTargetObserver: DATABASE_LOAD_ERROR error is outputted when building to Android via Patch & Build option using Vuforia

### ISSUE THREAD

**Issue by Artuzki00** [PTCInc/vuforia-engine#63]
**Summarize the bug:**
As the title says I have problem with model targets when building to android device using the patch function in Unity. I have been in contact with unity's support and have made a bug report there. Unity could replicate the bug but they found that it was coming from the Vuforia package so they could not do anything. The bug is has something to do with the model target database being not found.

**Observed problem**
When I build an android AR application using the unity's patch and run function, I get an error in Android Logcat saying that model target database is not found. In the application this results in the model target not working and my 3d model does not track at all. When using the unity's build and run the model target works and I get no errors but dynamically loaded buttons in my project does not work.

**Expected result**
 "AR Creating ModelTargetObserver...SUCCESS" message is outputted when using the Patch & Run option
Actual results: "Creating ModelTargetObserver...FAILED" message is outputted when using the Patch & Run option

**Other observations**
Notes:
-Issue does not reproduce in Unity Editor
-Errors:
Creating ModelTargetObserver...FAILED
Exception in callback: Failed to create ModelTargetObserver: DATABASE_LOAD_ERROR.

**Reproducible steps**
1. Open the attached user's project "test App.zip"
2. Select "TestScene.unity" in Build Settings
3. Use the Build And Run option with the device connected
4. Observe in the logcat the message "AR Creating ModelTargetObserver...SUCCESS" when the application is launched
5. Use the Patch And Run option in Build Settings
6. Observe in the logcat the message "Creating ModelTargetObserver...FAILED" when the application is launched

**Affected Vuforia Engine version:**
v10.17.4 and v10.18.4

**Affected platform:**
 - Workstation OS: Windows
 - Platform Unity
 - Platform version 2022.3.10f1, 2023.1.14f1, 2023.2.0b10, 2023.3.0a6

**Affected device:**
 - Name: Samsung galaxy s20
 - Model: SM-G981B/DS
 - OS: Android 12

**Screenshots / Video Recordings**
![Vuforia](https://github.com/PTCInc/vuforia-engine/assets/147391185/44a4a18d-f11d-4d13-989f-c198101499e8)

**Affected database**
If applicable, share your database / dataset which is affected in the issue you're experiecing.

**Device or platform logs**
```Share any logs from the platform or device.```

**Workaround**
No workarounds as far as i'm aware

**Additional comments**
Could not add the test project here because of size. 
Please ask for any other additional information.

**Comment by ptc-ddowning** [comment]
Thanks for the report. We'll take a look.

Can you share your use case for using the 'patch and run' feature in Unity? Assuming that this is the correct [description ](https://docs.unity3d.com/Manual/android-AppPatching.html#:~:text=For%20faster%20iterations%20during%20development,to%20the%20connected%20Android%20device) of the feature you're using

-Vuforia Support

**Comment by Artuzki00** [comment]
Yes, that is the feature i'm using. I'm using it mainly because its faster to deploy changes to the build but recently I've had to use the patch and run function only because as I said in the actual report when I use the build and run function the tracking works but buttons that the app loads dynamically doesn't appear at all.

**Comment by ptc-ddowning** [comment]
Thank you for the response, and clarification.

I would counter that we are likely dealing with two (2) different issues:

1. Model Targets device database will not load
2. Dynamically loaded buttons do not work

Agree with Unity that #1 may be related to Vuforia Engine's support of the 'patch and run' feature. 

However, my understanding is that Engine has nothing to do with #2 as UX elements, such as buttons, are a Unity feature.

Have you tried to reproduce #2 **without** Engine?

Thanks,
Vuforia Engine Support

**Comment by Artuzki00** [comment]
I actually haven't thought about the possibility that the problems might be unrelated because they appeared at the same time if I recall correctly. But I will investigate that possibility.

**Comment by ptc-ddowning** [comment]
Initial feedback from the team is that they were not able to reproduce the issue.

Thus, I would suggest that you attempt this workflow with our Core Samples to see if you can reproduce. If you can, please document the steps so that we can attempt to reproduce, as well.

Thanks,
Vuforia Engine Support

**Comment by Artuzki00** [comment]
I have done some testing and I'm positive that the issue relating the buttons is caused by Vuforia engine because after I removed it the buttons started working normally after using the build and run functionality in unity. 

And second thing. Would it be possible for me to send a test project to you somehow where I and the Unity support team have been able to replicate the problem?

**Comment by ptc-ddowning** [comment]
Hello @Artuzki00,

Thanks for the update. If you are asking about providing a Unity project repro-case to further investigate the issue with the 'patch and run' feature, that is best case to enable the team.

Thanks,
Vuforia Engine Support

**Comment by ptc-pscheper** [comment]
This issue is closed due to inactivity. Feel free to re-open or create a new bug report in the future.
