### ISSUE TITLE
MRTK3 Support

### ISSUE THREAD

**Issue by ottersity** [PTCInc/vuforia-engine#66]
**Summarize your feature feedback**
Compatibility with MRTK3

**Describe your feature**
Compatibility with MRTK3

**Use-case description**
I think MRTK3 has a lot of cool new features that are important for some of our future use cases, so compatibility with it would be appreciated.

**Business impact**
Easier Object Tracking to place match physical objects with virtual ones.

**Workaround**
No

**Additional context**
I can install vuforia and then mrkt3. After attaching the `Vuforia Behavior.cs` and `Default Initializiation Error Handler.cs` to the `Main Camera` of `MRTK XR Rig` I can deploy to hololens 2 without any errors. MRKT3 works fine, but vuforia don't detect my imagetarget (astronaut). There are no errors in the UnityPlayer.log. I used the same procedure which was working for me with MRKT2 and Vuforia.

**Comment by ptc-pscheper** [comment]
Hi there, 

As you noticed, we don't officially support MRTK3 as of today. Thank you for the feedback as we're continuously looking to improve the SDK. I know our team has been looking into it, but at the moment nothing is concrete. Could you highlight which features of MRTK3 are important for some of your (future) use-cases which are not found in the older versions?

**Comment by ottersity** [comment]
For us as research institute rapid prototyping is really important for us and mrkt3 has lots of improvement which makes building e.g. UIs much easier because it is based on the Unity-UI system.
In addtion mrtk3 is finally based on Unity XRI which really improves the cross-platform support.
Finally, mrtk2 will not be supported anymore so at some point we will be locked with an old unity version, to avoid this we would like to switch to mrkt3 as fast as possible - especially for new prototypes :-)

**Comment by ptc-epassaro** [comment]
Hi @ottersity, while we keep looking into this, there is a small update that might be useful for you.

Some of our customers have reported that Vuforia works on MRTK3 with one simple additional step.
After adding the `VuforiaBehaviour` and the `DefaultInitializationErrorHandler` components to the `Main Camera` in the `MRTK XR Rig`, select the `Camera Offset` GameObject and set its `Position` in the `Transform` to (0, 0, 0) and the `Camera Y Offset` value in the `XR Origin` component to 0.

This should correctly display the augmentations at the appropriate position on the targets.

If you try this, please let us know if it worked for you too!

**Comment by anjelomerte** [comment]
Hi:)
Just to clarify, are there any actual compatibility issues in terms of MRTK3 + Vuforia? I have been doing just that what @ptc-epassaro described for a couple of months now, working with image targets only though. Would be good to know if there is potential for further problems so I could plan in advance whether to use MRTK3 indeed or switch to MRTK2.

**Comment by Faith012** [comment]
Hi!
I tried to apply the steps described above and Vuforia is detecting my image, but for some reasons, in the first moment after my image is recognized I can se my game object which has to be just above my image, but after a very small while gameobject is going somewhere from his coordinates. In the console I can see that my image is still tracked normally but gameobject is missing from its position and is very far away. What could be the problem?
Thanks!

**Comment by ptc-epassaro** [comment]
Hi @Faith012, which versions of Unity, OpenXR and MRTK3 are you using? Also, are you sure that the camera Y offset and the position of the CameraOffset GameObject are set to 0 and don't change?

**Comment by Faith012** [comment]
Hi @ptc-epassaro  I am using Unity 2022.3.17f1, MRTK3 (the latest versions for all packages) and OpenXR Plugin 1.10.0. This are the latest for now from the Microsoft MR Feature Tool). Regarding the camera Y offset and other stuff you described I set them up as in the sollutions provided above.

**Comment by SangonomiyaSakunovi** [comment]
I also meet this trouble, why the position of my gameobject isn`t above my image? Really strange, maybe need more configs?

**Comment by ptc-epassaro** [comment]
Hi @SangonomiyaSakunovi, we have identified the problem and currently the recommendation is to keep the `MRTKInputSimulator` deactivated when testing Vuforia features in PlayMode. Please check out the conversation in this thread for more details: https://github.com/PTCInc/vuforia-engine/issues/108

**Comment by ashfaqueck** [comment]
So the discussion here seems like about Hololens...

Can MRTK 3 and vuforia combined work in MagicLeap 2?

@ptc-epassaro  @ptc-pscheper

**Comment by ptc-epassaro** [comment]
Hi @ashfaqueck, thank you for your question. Vuforia can work with MRTK3 on both HoloLens 2 and MagicLeap 2 when combined with OpenXR. The Vuforia documentation will soon be updated to show how to do exactly that.

We will post in this thread as soon as the updated documentation is online.

**Comment by ptc-thesbyro** [comment]
With the release of Vuforia Engine 10.24, MRTK3 is now fully supported for Magic Leap and HoloLens via a new Vuforia Digital Eyewear Unity sample. Check it out here: [Vuforia Digital Eyewear Sample](https://developer.vuforia.com/library/platform-support/vuforia-digital-eyewear-sample)

Thank you all for your feedback,
