### ISSUE TITLE
Missing VuforiaEngine.dll

### ISSUE THREAD

**Issue by dylan-infinitus** [PTCInc/vuforia-engine#68]
**Summarize the bug:**
I have successfully built a Unity Vuforia app for Android, everything works as expected. Now, I am looking to build a Windows standalone version of the same app. My Windows standalone build cannot find the `VuforiaEngine.dll`. The location where it is looking for the file doesn't exist i.e. `MyApp_Data/MonoBleedingEdge/VuforiaEngine.dll`.

**Observed problem**
When I build and run the Windows app, I am presented with an error about a missing `VuforiaEngine.dll`. I have upgraded my Vuforia version to the latest release (10.18) via the Unity Asset Store and also upgraded my Unity version to their latest release (2022.3.11f1). I also played with many settings, although I am still unable to run my Windows standalone build with Vuforia initialised.

**Expected result**
I expected the Windows standalone version to run similar to the Android version, using a connected webcam instead of the mobile device camera.

**Other observations**
I noticed in the Unity project package for Vuforia Engine AR, the plugins folder has sub-folders for Windows/x64. Inside here is a few plugins, most notably VuforiaEngine.dll (which my standalone build is struggling to locate). When inspecting this VuforiaEngine.dll plugin, I can see the support platforms does not include standalone builds (it only includes Editor). I am unable to edit this plugin directly.

**Reproducible steps**
1. Download Vuforia Engine from Unity Asset Store
2. Configure Vuforia Engine in your project
3. Build a Windows standalone development build
4. Run the build
5. See the error in the on-screen console log

**Affected Vuforia Engine version:**
v10.18.

**Affected platform:**
 - Workstation OS: Windows
 - Platform: Unity
 - Platform version: 2022.3.11f1

**Affected device:**
 - Name: Windows standalone app
 - OS: Windows 10

**Screenshots / Video Recordings**
![image](https://github.com/PTCInc/vuforia-engine/assets/69203866/18b13312-a615-4761-9062-5aea79166f8b)

**Affected database**
N/A

**Device or platform logs**
[player_log.txt](https://github.com/PTCInc/vuforia-engine/files/13162750/player_log.txt)

**Workaround**
There is no workaround for this.

**Additional comments**
N/A

**Comment by ptc-pscheper** [comment]
Hi there, please note that we do not support standalone Windows builds. We do however support UWP. I will close this bug as it is related to building to an unsupported platform.
