### ISSUE TITLE
Android Config Initialization Error, Failed to Initialize Vuforia Engine

### ISSUE THREAD

**Issue by anzilparviz29** [PTCInc/vuforia-engine#70]
My App works fine for the initial launch, then after that if  i launch the app, it gives the error Android Config Initialization Error, Failed to Initialize Vuforia Engine. Vuforia Team Please fix this Error.
![WhatsApp Image 2023-10-30 at 3 14 11 PM](https://github.com/PTCInc/vuforia-engine/assets/106994723/f23db06f-d2f9-4920-8c89-cff0b4ead131)

**Comment by ptc-pscheper** [comment]
Thank you for reaching out. I noticed that your issue does not follow the required format outlined in our contribution guidelines. To ensure effective and timely support, it is mandatory to follow the guidelines and use our provided templates when submitting a bug report or feature feedback. These templates help us gather essential information to assist you properly.

**As your post does not adhere to the guidelines, I will close this thread.**

However, I encourage you to re-submit your question or report using the appropriate template. I also recommend to try to build the [Core Samples](https://assetstore.unity.com/packages/templates/packs/vuforia-core-samples-99026) when reproducing the issue. Here’s how:

- Review the Guidelines: Please revisit our [Contribution Guidelines](https://github.com/PTCInc/vuforia-engine/blob/master/CONTRIBUTING.md) for posting requirements.
- Use the Template: Select the relevant template when creating a new issue and answer the questions comprehensively.

Thank you.

**Comment by slabarque** [comment]
I created #101 according to guidelines
