### ISSUE TITLE
DepthMasked objects are black

### ISSUE THREAD

**Issue by weezah** [PTCInc/vuforia-engine#72]
**Summarize the bug:**
Depthmasked object is rendered black over the camera background. Everything else in the scene is fine.

**Observed problem**
Using latest OSX silicon M2, Unity 2022.3, latest vuforia
It occurs on playmode on the mac but also when deployed on iphone14.
Camera clear flag is set to colour. Using depth will leave a trail on the depth masked object.

**Expected result**
The masked region shows the camera background image, not black pixels or a trail.

**Other observations**
I've messed with render queues with no success.
Using arfoundation/arkit with the same shader has correct results.

**Reproducible steps**
Add a cube, set the material to depthmask

**Affected Vuforia Engine version:**
v10.18.4

**Affected platform:**
 - Workstation OS: Mac]
 - Platform  Unity 
 - Platform version 2022.3

**Affected device:**
 - Name: Iphone
 - Model: 14
 - OS: ios 16.x

**Comment by ptc-pscheper** [comment]
Hi there, can you share the depth mask shader for us to reproduce the issue? Without reproducible steps we cannot support. Thank you!

**Comment by weezah** [comment]
I have created a new project to share with you but it worked there. The project were I was working was big and full of render queue modifications. I could figure it out and now it works fine.
Sorry for the trouble!

**Comment by ptc-pscheper** [comment]
No worries, thank you!
