### ISSUE TITLE
vuforia 10.19.3 on Android build Unity 2020.3.30f1 be gradle error

### ISSUE THREAD

**Issue by magisystem-mok** [PTCInc/vuforia-engine#73]
hello

i have problem on Android build on Unity 202.3.30f1

i just use Vuforia 9.8 and now update 10.19.3

get Android build result "succeeded" but also one error log

IndexOutOfRangeException: Index was outside the bounds of the array.
Vuforia.EditorClasses.GradlePropertiesParser+<>c.<FromString>b__3_1 (System.String v) (at <e2ac827c108347a08067e2bd69c6ad84>:0)
System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement] (TSource[] source, System.Func`2[T,TResult] keySelector, System.Func`2[T,TResult] elementSelector, System.Collections.Generic.IEqualityComparer`1[T] comparer) (at <351e49e2a5bf4fd6beabb458ce2255f3>:0)
System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] keySelector, System.Func`2[T,TResult] elementSelector, System.Collections.Generic.IEqualityComparer`1[T] comparer) (at <351e49e2a5bf4fd6beabb458ce2255f3>:0)
System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] keySelector, System.Func`2[T,TResult] elementSelector) (at <351e49e2a5bf4fd6beabb458ce2255f3>:0)
Vuforia.EditorClasses.GradlePropertiesParser.FromString (System.String content) (at <e2ac827c108347a08067e2bd69c6ad84>:0)
Vuforia.EditorClasses.GradlePropertiesParser.FromFile (System.String path) (at <e2ac827c108347a08067e2bd69c6ad84>:0)
Vuforia.EditorClasses.PostProcessAndroidBuild.ParseGradleProperties (System.String projectPath) (at <e2ac827c108347a08067e2bd69c6ad84>:0)
Vuforia.EditorClasses.PostProcessAndroidBuild.OnPostGenerateGradleAndroidProject (System.String path) (at <e2ac827c108347a08067e2bd69c6ad84>:0)
UnityEditor.Android.AndroidBuildPipelineInterfaces.OnGeneratePlatformProjectPostprocess (System.String path, System.Boolean strict) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline/Android/AndroidPostGenerateGradleProject.cs:39)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&) (at /Users/bokken/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:189)

and my application do not work any more
when i start application black screen and crash

i do armv7 off and using il2cpp already yet and also sdk min level was oreo
how can i fix this?

please i need your help

**Comment by magisystem-mok** [comment]
now i am updating unity to 2022.3.14

but that error was still remained

**Comment by ptc-pscheper** [comment]
Have you tried to build and deploy the [Core Samples](https://assetstore.unity.com/packages/templates/packs/vuforia-core-samples-99026)? If not, please do so and share your findings. If those can be built and deployed successfully we can take out your hardware from the equation.

**Comment by magisystem-mok** [comment]
i'm doing core samples deploy
it was OK, vuforia was work
i'm so confusing this......

what was my fault?

**Comment by ptc-pscheper** [comment]
I would suggest to go through the Migration Guide and validate if you went through all the steps: https://developer.vuforia.com/library/project-migration/how-migrate-unity-project. It seems this is related to your specific project and not Vuforia Engine, hence this issue will be closed.

**Comment by magisystem-mok** [comment]
After seeing this answer, I kept following the migration for a few days and tried re input vuforia again, but the error still remains.

I think the problem will be solved only if the function of the "Vuforia.EditorClasses.GradelePropertiesParser" is directly matched to my project
No matter how hard I look for it, it won't come out

If you let me know the location, I will use it directly for my project.

**Comment by magisystem-mok** [comment]
hello Tank you for Answer me again,
i do Disable my gradle.properties and delete that file
and now my Application was working! and can use vuforia too

When I did the test, I only Disable it, but I guess it was important to delete it completely, not just Disable

but, It bothers me, that error still remains in the unity editor's log
I didn't test the whole thing, so I can ask you a question again, 
but I think almost solved because application is working now,
so thank you so much.

And if there is a situation where I have to use the gradle.properties file again in the future, I would like you to give me your opinion on what to do

**Comment by ptc-pscheper** [comment]
Hi there, that is great to hear. You can use a custom gradle.properties file, but it might be that there was wrong information inside the one that was not deleted. If you run into a similar situation in the future, feel free to create a new bug report. For now, I will close this ticket.
