### ISSUE TITLE
Can you use Vuforia on ARMv7 (needed due to external tesseract library being built for 32-bit and won't work on ARM64 on Android)

### ISSUE THREAD

**Issue by garethmalc** [PTCInc/vuforia-engine#76]
I'm hoping someone can help me with something. I'm creating an Android App to use Tesseract OCR along with Vuforia to use the ARCamera to take a photo of text, then perform OCR for further processing.

Unfortunately the library i've downloaded from the following https://github.com/Neelarghya/tesseract-unity is only built for 32-bit Android and therefore won't run on ARM64 due to issues with the libtesseract.so binary file.

I really need to get this working ASAP and am wondering if there's a means of getting Vuforia to work on ARMv7 architecture so I can get moving on this. Any help anyone can provide would be greatly appreicated.

**Comment by ptc-pscheper** [comment]
Hi there, the only possibility is to disable ARCore which will degrade tracking for certain target types. If you disable ARCore in the Vuforia Configuration file, you should be able to built for 32-bit Android devices.

**Comment by garethmalc** [comment]
Hi Patrick,

Thanks for coming back to me on this. Could you advise which marking
targets would still be available as I'm hoping I might be able to work
around this

**Comment by ptc-emaggio** [comment]
All targets are available except Area Targets. Model Target will work with reduced robustness. Extended tracking (the ability to report the target position when the target is out of view) will not work for any of the targets.

**Comment by ptc-pscheper** [comment]
Vuforia Engine can be used on 32-bit devices with reduced robustness and is not advised. For this specific use-case it is possible by disabling ARCore.

**Comment by garethmalc** [comment]
Hi All, just wanted to check if you think Ground Detection is possible when using Vuforia built for ARMv7 32-bit architecture?

**Comment by ptc-emaggio** [comment]
@garethmalc without ARCore ground-plane detection is by all means not available on most Android devices.

**Comment by garethmalc** [comment]
Thanks for coming back to me @ptc-emaggio 

I'm really stuck as I need to proceed with ARMv7 due to issues with the imported tesseract wrapper being designed for this architecture. 

Would you have any feedback in regards which tracking types available in ARMv7 would provide the closest match of functionality to Ground Detection? Basically I'm going to be trying to use the first word of text contained on a page within camera view to then overlay a "virtual page" with the recognised text with other features etc. My thoughts were that ground-plane detection would have been ideal but am obviously having issues due to the enforced ARMv7 design! Any steer would be massively appreciated.

**Comment by garethmalc** [comment]
Alternatively, would a potential workaround be to incorporate an older version of ARCore into my project e.g. V1.22? Would that be a possibility that might work for this limited use case?

**Comment by ptc-emaggio** [comment]
Unfortunately Google is deprecating 32-bit support for ARCore. There isn't much we can do about it (see here https://developers.google.com/ar/64bit). Vuforia ARCore minimum supported version is 1.32 (at the time of writing). An older version might still work but we cannot guarantee it. Clearly alternatives to tesseract for text recognition on Android exist. For example https://developers.google.com/ml-kit/vision/text-recognition/v2/android
