### ISSUE TITLE
[Unity] Find VuforiaBehaviour Instance if the gameobject is inactive

### ISSUE THREAD

**Issue by tsoen** [PTCInc/vuforia-engine#78]
**Describe your feature**
Hello,
Using Vuforia 10.19 on Unity.
It would be nice if `VuforiaBehaviour.Instance` could find the instance even if the GameObject is inactive in the scene.

**Use-case description**
Our application do not start the AR Camera at the beginning, the user decides when to activate it.
However we cannot use `VuforiaBehaviour.Instance` to find and enable the object because it returns null, we have to serialize the object from the scene to be able to access it.

**Business impact**
Quality of life.

**Workaround**
Serialize the object from the scene.

**Comment by ptc-pscheper** [comment]
Hi there, thank you for your feedback and apologies for the delay in response. In the meantime the team has found a solution where the Instance itself will be not null, but all the related fields will be. This way you can enable it if required. This change will be pushed in one of the next releases.

**Comment by ptc-pscheper** [comment]
@tsoen The team developed a fix where the instance of `VuforiaBehaviour.Instance` will be not null. Please note that all related fields will be null, because Awake() is not called yet. This is now available in v10.21!
