### ISSUE TITLE
Unexpected camera displacement when returning to an AR session on Android

### ISSUE THREAD

**Issue by Din-Wan** [PTCInc/vuforia-engine#8]
**Summarize the bug:**
When returning to an AR session, the camera shifts unexpectedly after some time. The shift distance is the same the distance camera moved from the origin in the previous AR session.

**Observed problem**
The camera position seems to be saved from the previous session, regardless of whether `VuforiaBehaviour.Instance.DevicePoseBehaviour.Reset()` is called.

**Expected result**
There should not be any displacement applied to the camera since the device pose is reset. I want the behaviour from when we establish the AR session for the first time.

**Other observations**
This does not seem to occur on iOS which leads me to believe that it is an ARCore specific behaviour.

**Reproducible steps**
Scene modified with cube game object in fixed position at world origin with along with camera
1. Enter AR session
2. Observe cube directly under
3. Walk a few metres forward
4. Reset device pose behaviour and close AR session
5. Move back to original position
6. Restart AR session
7. Cube is no longer directly under

**Affected Vuforia Engine version:**
Version: 10.13.3

**Affected platform:**
 - Workstation OS: Mac
 - Platform: Unity
 - Platform version: 2021.3.17f1

**Affected devices:**
 - Name: OnePlus 6
 - Model: A6003
 - OS: Android 11

- Name: Samsung Galaxy S20 Ultra 5G
- Model: SM-G988B/DS
- OS: Android 12

**Device or platform logs**
This is what I noticed in the logs when the displacement occurs:
```
2023-03-17 13:48:51.105 19387-19692 native                  com.vuforia.engine.coresamples       I  I0000 00:00:1679014131.105461   19692 pose_manager.cc:279] World pose node changing to MapId:1c54b09b-dfcd-2bbb-9274-c39bc2217987 with 1 opt.
```

**Workaround**
Manually setting Vuforia camera transform position to world origin after the device pose status changes to TRACKED-NORMAL, but the displacement can still occur after this.

**Comment by Din-Wan** [comment]
Just an update to this, we managed to stop the displacement by deinitializing vuforia and reinitializing it.

**Comment by ptc-pscheper** [comment]
Hi there, does that mean that by deinitializing / reinitializing the issue is solved?

**Comment by Din-Wan** [comment]
Yes, the issue is solved.
