### ISSUE TITLE
Vuforia does not work with Arfoundation on Android build

### ISSUE THREAD

**Issue by ShonubiSamuel** [PTCInc/vuforia-engine#81]
**Summarize the bug:**
Hi, the issue I'm facing is that Vuforia does not work with arfoundation on Android build, like it does not detect the target images.
I have an in game debugger (like a console on in my android game) so with that i was able to confirm that there is no in game error.

I followed the step documented in this page https://developer.vuforia.com/library/unity-extension/vuforia-engine-and-ar-foundation 
but nothing works

I'm using;
Unity 2022.3.4f1
Vuforia Engine 10.19
Redmi Note 9

**Comment by ptc-pscheper** [comment]
I suggest debugging your device with Logcat and I recommend to build the [Core Samples](https://assetstore.unity.com/packages/templates/packs/vuforia-core-samples-99026) to test if Engine itself works on your device as it is not a recommended device.
