### ISSUE TITLE
Issue importing Vuforia SDK to Unity 2021

### ISSUE THREAD

**Issue by mauako** [PTCInc/vuforia-engine#83]
I get error when importing the vuforia engine 10.20 into Unity 2021, please check the photo below.
How do I fix it?
![Uploading Screenshot 2024-01-10 220413.png…]()

**Comment by ptc-emaggio** [comment]
the minimum supported version for recent engine releases is 2022.3 https://developer.vuforia.com/library/platform-support/supported-versions
