### ISSUE TITLE
Resolution problem using GetCameraImage

### ISSUE THREAD

**Issue by lawl2** [PTCInc/vuforia-engine#85]
**Summarize the bug:**
When using GetCameraImage to create a new Vuforia.Image the resolution of the output image is always 640x480 also if the simulation is set with a different resolution

**Observed problem**
Using GetCameraImage I always get a cropped image 640x480 also if the simulation uses for example 1536x2048 (Apple Ipad Mini 4 resolution)

**Expected result**
I would like to have an image with the same resolution of the simulation

**Other observations**
Share any other observations that you made while experiencing the bug.

**Reproducible steps**
1. changing simulation to a different resoution (for exampe Apple Ipad Mini 4)
2. creating a C# script
3. instanciate a camera device
4. set fram format using a pixel format RGB888
5. create a Vuforia.Image using GetCameraImage with a pixel format RGB888
6. using Debug.Log and printing width and heght. They don't depend on simulation resolution

**Affected Vuforia Engine version:**
v10.12.3.

**Affected platform:**
 - Windows
 - Unity
 - 2022.3

**Affected device:**
 - Name: [e.g. Google Pixel 6a]
 - Model: [e.g. GX7AS]
 - OS: [e.g. Android 12]

**Comment by ptc-epassaro** [comment]
Hello @lawl2, thank you for your report. Does this behaviour appear both in PlayMode in the Editor and on device or only in the Editor?

**Comment by lawl2** [comment]
We are developping an application for desktop right now, at runtime the only resolution of the output image we save is always the one we indicated in the previous message, it does not be affected by simulation  resolution in play mode

**Comment by ptc-epassaro** [comment]
Hello @lawl2, as the name suggests, the `GetCameraImage()` method returns the image that Vuforia receives from the camera of the device. Because of that, the resolution of the image does not change with the resolution of the screen or of the Game window in the Unity Editor.

Can I ask you, what do you need the images for? Maybe we can look for an alternative solution.

**Comment by lawl2** [comment]
Hello, we use GetCameraImage() to get the image and then we apply edge detection algorithms saving the resulting image.

**Comment by ptc-pscheper** [comment]
This issue is closed due to inactivity. Feel free to re-open or create a new bug report in the future.

**Comment by riccardokhm** [comment]
Hi! 
I am reopening this discussion to ask if  GetCameraImage is supposed to always returning a low resolution image (640 x 480) regardless of the d device resolution. Is Vuforia working at such low resolution?

**Comment by lawl2** [comment]
@ptc-epassaro we tried to use WebCamTexture using the code you linked but it gives an error when Vuforia is initialized 
![screen](https://github.com/PTCInc/vuforia-engine/assets/105045290/c5a4a39e-1fa4-457b-b013-30c05a58e7b3)
It's is able to see devices and play the selected camera but when it starts the coroutine it shows this error
