### ISSUE TITLE
Guideview preview images all the same after creating the database on the Model Target Generator

### ISSUE THREAD

**Issue by riccardokhm** [PTCInc/vuforia-engine#9]
**Summarize the bug:**
From the latest releases of the Vuforia Engine, I noticed that when trying to visualize the preview image for each guideview they are no more meaningful, meaning that they are all the same and often equal to the first guideview created. Is it a bug or a precise choice from the technical team?

**Observed problem**
Preview  images of each guideview is equal to the first one. 

**Other observations**
This behaviour was not reported up to the Vuforia Engine v10

**Affected Vuforia Engine version:**
v10.12.3.

**Affected platform:**
All platforms (I am developing for Android and iOs)

**Affected database**
All databases created by the Model Target Generator.

**Additional comments**
Add any other details about the problem here.

Add any other details about the problem here.

**Comment by ptc-pscheper** [comment]
Hi there, thank you for your bug report. Are you referring to the preview images in the Model Target Generator when creating multiple Guide Views?

![image](https://user-images.githubusercontent.com/88328882/227278306-b96554e7-ca47-4222-addd-bf24e60aa7ba.png)

**Comment by riccardokhm** [comment]
Hi! Nope, actually when I generate the model target with the guideviews, in the dataset folder preview images of each guideview are all the same. Here an example.
![Capture](https://user-images.githubusercontent.com/63868396/227459964-547cdd44-dd24-40e1-8b10-4711f2bdb1bb.JPG)

Since I'll be using the .png preview images to let the user understand the point of view from which approach the target, in this case the difference won't be visible since preview images do not change. On Vuforia Engine 9 instead, the MTG successfully exported all the preview images as depicted at the moment of creating the guideview.

**Comment by ptc-pscheper** [comment]
Hey there, this is very strange. For me the guide view images are shown correctly:

![image](https://user-images.githubusercontent.com/88328882/227525459-a4140793-66b9-4079-b306-6c919ac08588.png)

Could you update to the v10.14.4 MTG and see if the issue persists?

**Comment by riccardokhm** [comment]
Hi, unfortunately the issue persists, do you have any other suggestion?
![Capture](https://user-images.githubusercontent.com/63868396/227544796-810c918a-3b80-4e3b-be55-633a0f86f87b.JPG)

**Comment by riccardokhm** [comment]
Hi! It seems solved as stated in my email. Basically, it seemed due to the fact that I was overwriting on the same destination folder of a previous version of the dataset. 

SOLVED: Try to delete the folder (if a previous version of the same dataset exists) and re-create the model target dataset.

**Comment by ptc-pscheper** [comment]
Great to hear. Thank you for the update!
