### ISSUE TITLE
The autofocus won't focus on Galaxy S20 can't scan Vumark

### ISSUE THREAD

**Issue by KevinLachance** [PTCInc/vuforia-engine#91]
Summarize the bug:
We have an application made with unity 2021.3.24. We use Vuforia 10.20.3 for ground tracking and Vumark. On a Samsung Galaxy S20 FE 5G (Android 10) or Samsung Galaxy S20 Plus (Android 13) the camera focus won’t work. We are not able to scan Vumark on these devices.

Observed problem:
The focus/autofocus won't work and we are not able to scan vumark

Expected result:
I expect a camera focus and the vumark can be scanned

Other observations:
Even if we put a finger on the camera or move the device back to front nothing happen the camera stay blurry on near object 

**Reproducible steps**
1. build a project with vuforia 
2. try to scan a vumark
3. see the camera stay blurry with the Vumark

Affected Vuforia Engine version:
Vuforia Version 10.20.3

Affected platform:
 - Workstation OS: Windows 10
 - Platform Unity
 - Platform version : 2021.3.24

Affected device a dev in our team have this device:
 - Name: Samsung Galaxy S20 Plus
 - Model: SM-G986W
 - OS: Android 13

Affected device our external qa team have this device:
 - Name: Samsung Galaxy S20 FE 5G
 - Model: i dont have the model
 - OS: Android 10

Screenshots / Video Recordings: 

Here the settting on the scriptable object : 
![image](https://github.com/PTCInc/vuforia-engine/assets/126600481/1b08c300-f4e7-456c-ab18-198cf8a60667)

I have a code snippet to force the focus only on android at every 5 seconds:
![image](https://github.com/PTCInc/vuforia-engine/assets/126600481/23f72a77-82c3-42c8-bcf0-9c5489f11c49)

I can provide you more inof by e-mail or here iff you need

kind regard,

Kevin

**Comment by ptc-pscheper** [comment]
Hi there, can you try upgrading your Unity version to 2022.3 or above? The minimum supported Unity Editor version has been raised to 2022.3 since v10.17.4.

**Comment by ptc-pscheper** [comment]
This issue is closed due to inactivity. Feel free to re-open or create a new bug report in the future.
