### ISSUE TITLE
Inconsistent Visibility of Area Targets in Play Mode: Some Area Targets Not Appearing

### ISSUE THREAD

**Issue by Muhammad-Ali-70** [PTCInc/vuforia-engine#99]
**Summarize the bug:**
I am Making an indoor AR Navigation App for my Campus, The problem in my project is Area targets are not consistently visible in play mode, with only a few targets appearing while others do not. The issue persists despite attaching the MultiArea.cs script from Vuforia documentation to the parent object of all area targets.

**Observed problem:**
When running the game in play mode (simulator), only area targets from the first floor are visible. Additionally, only some area targets from the first floor appear, while others remain invisible. Area targets from the second and third floors are not displayed at all. Furthermore, the clipping height of certain area targets becomes less than 1 without manual intervention.

**Expected result:**
All area targets, including those from the Ground, first, and second floors, should be visible and rendered properly in play mode. The MultiArea.cs script should enable the simultaneous tracking of multiple area targets across different floors.

**Other observations:**
- The issue persists across multiple test runs in the simulator.
- No error messages or warnings are displayed during runtime.
- Attaching the MultiArea.cs script to the parent object of all area targets did not resolve the issue.

**Affected Vuforia Engine version:**
v10.20.3.

**Affected platform:**
Workstation OS: Windows 10
Platform: Unity
Platform version: 2022.3.4f1

**Screenshots / Video Recordings:**

1. **Basic Project Structure. (Three Floors)**

![Project Structure](https://github.com/PTCInc/vuforia-engine/assets/113369931/a2123596-9d86-42b8-b998-441d998b562a)

**2. When Game is Run in Playmode. Area Targets of Second Floor are not shown and Some Area Targets of First Floor**
![Playmode](https://github.com/PTCInc/vuforia-engine/assets/113369931/73166ffb-c96b-44a5-a655-dfadd118dfdb)

**Affected database:**
AreaTarget Database Made with Vuforia Creator App. And Then Imported to Unity.

**Workaround:**
No workaround currently available.

**Comment by ptc-epassaro** [comment]
Hello @Muhammad-Ali-70, thank you for the detailed report. The team is looking into this issue and will keep you posted on the progress.
In the meantime, would it be possible for you to send us the logs from this project? It would be great for us to get as much info as possible.

**Comment by ptc-pscheper** [comment]
This issue is closed due to inactivity. Feel free to re-open or create a new bug report in the future.
